### ISSUE TITLE
set up GENOVAresult object

### ISSUE THREAD

**Issue by teunbrand** [robinweide/GENOVA#108]
Codename: Discovery

**Comment by teunbrand** [comment]
For the following:

- APA
- ATA
- PESCAn
- RCP
- Saddle

**Comment by teunbrand** [comment]
Group by sample or by result type? 

Below are conceptual options.

Option 1:

```
discovery <- structure(list(
  sampleA = list(
    result1, # e.g. observed over expected
    result2  # e.g. background or signal
  ),
  sampleB = list(
    result1,
    result2
  )
), class = "assayX_discovery", "discovery", "list")
```

Option 2:

```
discovery <- structure(list(
  result1 = array(
    sampleA, 
    sampleB
  ),
  result2 = array(
    sampleA, 
    sampleB
  )
), class = "assayX_discovery", "discovery", "list")
```

Option 1 is easy to merge the results of different samples, option 2 is easy for computation and visualisation. @robinweide do you have strong opinions?

**Comment by robinweide** [comment]
I would go for option 2. This would also allow for easy substitution of results by the user afterwards (e.g. pushing the same expected matrices for multiple samples).

**Comment by robinweide** [comment]
> For the following:
> 
> * [ ]  APA
> * [ ]  ATA
> * [ ]  PESCAn
> * [ ]  RCP
> * [ ]  Saddle
* [ ]  inter/intra TAD contacts
* [ ]  domainogram

**Comment by teunbrand** [comment]
All these functions now have associated discovery classes.
