### ISSUE TITLE
Free ourselves from reshape2 / dplyr dependencies

### ISSUE THREAD

**Issue by robinweide** [robinweide/GENOVA#110]
Sure, I think it is only `group_by()` and `summarise()`, which could be converted to an `aggregate()`-call.

`Melt()` is indeed easiest to just copy.

**Comment by teunbrand** [comment]
(Edited title for clarity) 
E.g. make/copy reshape2::melt (at least I think that is the only one)

**Comment by teunbrand** [comment]
reshape2 dependent functions:

- [ ] melt `visualise.APA.ggplot`
- [ ] melt `visualise.ATA.ggplot`
- [ ] melt `cov2d`
- [ ] melt `quantify ATA`
- [ ] library, but comment out in `compartment.score`
- [ ] melt `insulation.heatmap`
- [ ] melt `PESCAn` (old version)
- [ ] acast `APA` (old version)
- [ ] melt `saddleFunctions`

**Comment by teunbrand** [comment]
dplyr dependent functions:

- [ ] data_frame `RCP_OLD`
- [ ] data_frame, filter `RCP2`
- [ ] arrange, filter `insulation.callTAD`
- [ ] group_by, summarise `visualise.RCP.ggplot`
- [ ] group_by, summarize `insulation.heatmap`
- [ ] summarise, `saddleFunctions`

**Comment by robinweide** [comment]
> dplyr dependent functions:
> 
> * [ ]  data_frame `RCP_OLD`
> * [ ]  data_frame, filter `RCP2`
> * [ ]  arrange, filter `insulation.callTAD`
> * [ ]  group_by, summarise `visualise.RCP.ggplot`
> * [ ]  group_by, summarize `insulation.heatmap`
> * [ ]  summarise, `saddleFunctions`

group_by/summarise can be exchanged by the dt[i,j,by]

**Comment by teunbrand** [comment]
We probably could also get rid of grid if we go all in on facets and discard all `grid.arrange`. Not that it matters, because grid is a dependency of ggplot2, but still.

**Comment by robinweide** [comment]
> We probably could also get rid of grid if we go all in on facets and discard all `grid.arrange`. Not that it matters, because grid is a dependency of ggplot2, but still.

yes, I thought we already made this decision?

**Comment by teunbrand** [comment]
```
library(reshape2)

arr <- array(1:60, dim = c(3,4,5))

mb <- microbenchmark(
  basemelt = basemelt(arr),
  reshapemelt = melt(arr),
  times = 10000
)

mb
```
```
Unit: microseconds
        expr     min       lq     mean   median       uq      max neval
    basemelt 210.942 232.8235 260.5476 241.6015 257.4515 26284.59 10000
 reshapemelt 346.650 363.9020 391.8878 374.7995 399.9175 18232.19 10000
```

**Comment by robinweide** [comment]
construct experiment is free from this by using dt[i,j,by]

272cf99:

- `loadContacts()` is done and works for .cooler, .hic and hicpro
- z-score normalisation is refactored
- overhauled the contacts-object (**beware: all functions in dev will fail forthe coming days**)

**Comment by robinweide** [comment]
I removed their dependency in `DESCRIPTION`

**Comment by teunbrand** [comment]
It is no longer in the description and Travis CI/R CMD check returns no errors/warnings/notes about these, so I'd say it is safe to assume we removed these dependencies.
