### ISSUE TITLE
virtual 4C

### ISSUE THREAD

**Issue by robinweide** [robinweide/GENOVA#123]
Base this on the new APA-function

**Comment by robinweide** [comment]
update: main function works, visualise not: 7fac99c

**Comment by robinweide** [comment]
visualise.virtual4C_discovery now works 7cd990b

I still need to:

-  streamline both
-  enable list of exps

**Comment by robinweide** [comment]
392042b : 
made everything neater and added man-entries

**Comment by robinweide** [comment]
![virtual4C](https://user-images.githubusercontent.com/7115143/66104479-fe9dac00-e5b8-11e9-8122-8ee589db839b.png)
 This is the current stage:

- [ ] anchor
- [ ] option to add bed underneath (here: loop anchors called with HICCUPS)

**Comment by robinweide** [comment]
someday:

- [ ] multiple Hi-C (both as input for  virtual_4C and as bundle for vis)
- [] multiple beds in vis

**Comment by teunbrand** [comment]
You can now have multiple viewpoints in visualisation when bundling experiments. Also, multiple beds are an option.

```
bed1 <- data.frame("chr1", c(25e6, 125e6), c(50e6, 150e6))
bed2 <- data.frame("chr1", 75e6, 100e6)
bedlist <- list(bed1, bed2)

v4c1 <- virtual_4C(exp, data.frame("chr1", 25e6, 30e6))
v4c2 <- virtual_4C(exp, data.frame("chr1", 75e6, 80e6))

v4c <- bundle(v4c1, v4c2)

visualise(v4c, bedlist = bedlist, 
          bed_colours = c("dodgerblue", "limegreen"))
```

![image](https://user-images.githubusercontent.com/49372158/68758693-9659d580-060e-11ea-933e-23adef187f0d.png)

**Comment by teunbrand** [comment]
Closing this, as it is now able to do multiple experiments, multiple viewpoints can be bundles and multiple beds can be visualised.
