### ISSUE TITLE
Thoughts on containers for multiple experiments

### ISSUE THREAD

**Issue by teunbrand** [robinweide/GENOVA#126]
It would be nice if we someday could have a container for multiple experiments of the same resolution, that is slightly more sophisticated than having a list of multiple `contacts` objects.

Main benefit could be speed: matrix lookup functions can become faster because we don't have to iterate over experiments, but can extract subsets of the Hi-C matrix for multiple experiments in one go. Additional benefit could be more convenient organisation when the number of experiments get quite large, e.g. if we go single-cell Hi-C or otherwise have a large collection of samples. Furthermore, it would circumvent storing identical `ABS` slots in several experiments.

Major downside would be that probably a lot of code would have to refactored to take this into account.

I can see two ways of implementing this, both at the level of the `ICE` slot. Either we go from a sparse triplet matrix to sparse quadruplet array, with an extra index column indicating the experiment number. This would make the data slot longer. In example below `V3` indicates the experiment.

```
> ICE
```
```
V1   V2   V3    V4
1    1    1     5.586
1    1    2     5.721
1    2    1     2.546
1    2    2     3.020
```
Or we could have an extra column for every experiment containing the data, making the data slot wider:
```
> ICE
```
```
V1   V2   V3   V4
1   1   8.651  7.912
1   2   NA     5.168
1   3   3.812  4.002
1   4   1.293  NA
```

Both methods have their drawbacks. The first method would probably increase the time data.table takes to do `ICE[list(x, y)]` since the number of indices scale linearly with the number of experiments. Also storing the extra indices is not particularly memory efficient. The second method has the drawback that `NA`s would have to be stored when a particular bin is present in the one experiment  but not in the other.

**Comment by robinweide** [comment]
We have toyed with this idea in the past. The problem lies in the fact that it actually is less memory-efficient because of the introduced semi-sparsity. 

I do agree that this would be prettier for scHi-C. Maybe we could make a specific 'contacts'-class for those.

**Comment by teunbrand** [comment]
We can reopen this once it becomes more necessary
