### ISSUE TITLE
check all functions to handle contacts-object

### ISSUE THREAD

**Issue by robinweide** [robinweide/GENOVA#129]
Strike-though: will not be done due to deprecation in V1

- [x] APA
- [x] ATA
- [x] PESCAn
- [x] RCP
- [x] centromere.telomere.analysis
- [x] chromosomeMatrix
- [x] cis.compartment.plot
- [x] cisTotal.perChrom
- [x] cisTotal.scores
- [x] compartment.score
- [ ] ~~construct.experiment~~
- [x] differential.TAD.dotplot  
- [x] differential.TAD.scatterplot
- [x] draw.centromere.telomere
- [x] fastDI
- [ ] ~~fields.interp.surface~~
- [x] genome.wide.insulation
- [x] hic.matrixplot
- [x] insulation.callTAD
- [x] insulation.domainogram
- [x] insulation.heatmap
- [x] insulation.plot.dual
- [x] insulation.plot.single
- [x] insulation.score
- [x] intra.inter.TAD.contacts
- [ ] ~~quantifyAPA~~
- [x] saddle
- [x] select.subset
- [x] shuffleHiC
- [x] trans.compartment.plot    
- [ ] ~~visualise.APA.base~~
- [ ] ~~visualise.APA.ggplot~~
- [ ] ~~visualise.ATA.ggplot~~
- [ ] ~~visualise.PESCAn.ggplot~~
- [ ] ~~visualise.RCP.ggplot~~
- [ ] ~~visualise.compartmentStrength~~
- [ ] ~~visualise.saddle~~
- [x] ARA
- [x] print-methods
- [x] visualise-methods
- [ ] quantify-methods

**Comment by teunbrand** [comment]
`fields.interp.surface` is still used in `centromere.telomere.analysis`, I think.

**Comment by teunbrand** [comment]
Should be fixed now by #135. The quantify methods is a discussion for #111.
