### ISSUE TITLE
Visualising APAs

### ISSUE THREAD

**Issue by deWitLab** [robinweide/GENOVA#13]
I get the following error message

> loop.apa <- APA(exp.wt, loops, size=41, verbose=T)
> visualise.APA.ggplot(list(loop.apa), title="Test Run")
> Error in `$<-.data.frame`(`*tmp*`, "sample", value = integer(0)) : 
>   replacement has 0 rows, data has 8793311

**Comment by robinweide** [comment]
I think the problem is that the output of APA itself is a list. 
`visualise.APA.ggplot(list(loop.apa$APA), title="Test Run") should work file.
`
We should make sure that visualise.APA.ggplot recognises this and handles it automatically.

**Comment by robinweide** [comment]
Same as https://github.com/robinweide/GENOVA/issues/17
