### ISSUE TITLE
load speed straw

### ISSUE THREAD

**Issue by robinweide** [robinweide/GENOVA#132]
stawr is very slggish. Is this due to the lappy?

**Comment by teunbrand** [comment]
This one?
```
  chrom_name_length = lapply(1:n_chrs, function(x){
    chrom = readBin(file2read, character(), size = 1)
    len = readBin(file2read, integer(), n = 1)
    data.table::data.table(chrom, len)
  })
```

**Comment by robinweide** [comment]
Yeah, I don't think it is. But it is the only part that is in our control (other than loading matruces with parallel::mclapply)

**Comment by teunbrand** [comment]
I think it might also have to do with the `tryCatch()` statement. Running it outside that statement seems to run in a few seconds for 25k resolution matrix for human chr1/chr1, whereas inside the `tryCatch()` it takes a long time.

**Comment by robinweide** [comment]
Yes, we are basically running blind in terms of the chromosome-maps
present. If we know which are there (e.g. chr1-chr1) and which are not
(e.g. scaffoldX007-chrM), we can remove this tryCatch. Maybe we can nick
this from the metadata?

Op ma 25 nov. 2019 16:28 schreef teunbrand <notifications@github.com>:

**Comment by teunbrand** [comment]
Forgot to mention that the refactoring of splitJuicerData in 354e4a3d636f60ea2f2c64ac060c8f55d527d215 might have increased the speed a tiny bit, but not a lot.

**Comment by robinweide** [comment]
this is not our problem. Lets hope on a new straw-version
