### ISSUE TITLE
ATA: replacement has lenght zero

### ISSUE THREAD

**Issue by robinweide** [robinweide/GENOVA#137]
**Describe the bug**
When running this bed-entry (the chrom2 one) it will throw the error. maybe an issue with out-of-bounds issues?

**To Reproduce**
`bed <- structure(list(V1 = structure(c(1L, 1L, 12L), .Label = c("chr1", 
"chr10", "chr11", "chr12", "chr13", "chr14", "chr15", "chr16", 
"chr17", "chr18", "chr19", "chr2", "chr3", "chr4", "chr5", "chr6", 
"chr7", "chr8", "chr9", "chrX"), class = "factor"), V2 = c(195205000L, 
196795000L, 3005000L), V3 = c(196795000L, 197192716L, 4805000L
)), row.names = 235:237, class = "data.frame")
`

contact_list is a list of mm10 Hi-C contacts
`ATA_results <- ATA(contact_list,  bed = bed[,1:3])`

**Comment by teunbrand** [comment]
For me this runs without errors on the Hap1 WT/Wapl KO data at 20kb, even though organism is different. What `load_contacts()` call do I need to use to reproduce the error?

**Comment by robinweide** [comment]
I used mm10 (mouse) data. Maybe that’s there problem?

Op ma 30 sep. 2019 om 12:09 schreef teunbrand <notifications@github.com>

**Comment by teunbrand** [comment]
Do you have the signal_path/indices_path for data so I could check?

**Comment by teunbrand** [comment]
Yep definitely out of bounds issue.

Last entry in indices for chr1:
```
> tail(exp1$IDX[V1 == "chr1", ], 1)
     V1        V2        V3   V4
1: chr1 195460000 195471971 9774
```

The bed entries:

```
> bed
      V1        V2        V3
235 chr1 195205000 196795000   # end is out of bounds
236 chr1 196795000 197192716   # entire entry is out of bounds
237 chr2   3005000   4805000
```

These bed entries get converted to the following anchors:

```
> anchors_ATA(exp1$IDX, bed)
An 'anchors' object of type 'TADs' of length 3:
      [,1]  [,2]
[1,]  9721  9774
[2,]  9774  9774 # would result in 1 pixel lookup
[3,] 63310 63490
```

There might be two ways to fix this:

1. We would filter out anchor-entries for ATA wherein the x-position equals or is greater than the y-position in `anchors_ATA()`, which solves this specific issue.
2. We return `NA` in `bed2idx()` if the location is beyond the end of the chromosome, which solves this problem at a more fundamental level, but I kind of like that you don't have to give `bed2idx` perfect coordinates and you get the last index if you go beyond the end of the chromosome.
