### ISSUE TITLE
Extended loop-anchors?

### ISSUE THREAD

**Issue by robinweide** [robinweide/GENOVA#139]
Can we make extended loops like in Haarhuis & vanderWeide et al.?

Say, you give a loop.bedpe and a maximal distance And produce all extended loops?

**Comment by teunbrand** [comment]
We could.

Notes to self:

Working definition of an extended loop: 
All possible combinations of loop anchors within a specified distance excluding the original loops.

Implementation example:
```
anch <- anchors_extendedloops(IDX = exp$IDX, bedpe = loops, dist_thres = c(0, 1e6))
APA(list(WT_exp, KO_exp), anchors = anch)
```
