### ISSUE TITLE
Add Ren-lab load

### ISSUE THREAD

**Issue by robinweide** [robinweide/GENOVA#141]
I already did this, but needs to put into a function: https://github.com/robinweide/GENOVA/blob/master/R/notes/fullToHicPro

Basically loads and transforms the full-matrix input of Ren's lab to GENOVA-ready.

**Comment by teunbrand** [comment]
The link gives me a 404, but I think it might be nice in general to have the `Matrix` package in the imports/suggests to facilitate all kinds of sparse matrix conversions to also make GENOVA more compatible with other tools out there.

**Comment by robinweide** [comment]
True. I think we can let the small fraction of non-HiCpro, -juicer, -cooler ask questions here regarding loading their data.
