### ISSUE TITLE
Error running compartment_score at 10kb

### ISSUE THREAD

**Issue by robinweide** [robinweide/GENOVA#142]
This will run fine with 40kb data, but the 10kb equivalent leads to this break:

`CS_out <- compartment_score(list("WT" = WT_new, "KO" = KO_old), bed = bed[,1:3])`

> Error in `[.data.table`(idx, , CJ(V1 = V4, V2 = V4), by = list(chr = V1)) : 
>     negative length vectors are not allowed

I've spent quite some time to trace this, but it seems to be quite elusive. Option to add a lower bound on the resolution?

**Comment by teunbrand** [comment]
I'll have a look next week
