### ISSUE TITLE
Sign compartmentscore error

### ISSUE THREAD

**Issue by teunbrand** [robinweide/GENOVA#145]
In bed2idx: subset out of bounds

**Comment by teunbrand** [comment]
@robinweide Could you point me to the bed file that gave this error?

**Comment by robinweide** [comment]
It was the Hap1 narrowpeak of K4mono

**Comment by teunbrand** [comment]
Appears to be a consequence of providing the `bed` argument as data.table object. Easily fixed by coercing to data.frame within bed2idx.

**Comment by teunbrand** [comment]
I consider this bug fixed
