### ISSUE TITLE
chequer

### ISSUE THREAD

**Issue by robinweide** [robinweide/GENOVA#155]
A way to quantify the "chequeredness" of a locus.
Basically, from a 1D-location, quantify the amount of A/B switches:

- at an compartment-border: a high number
- at a TAD-border: a low number

**Comment by teunbrand** [comment]
Just a thought I'd like to add; compartment scores for the WAPL KO fluctuate (A/B switch) a lot but I wouldn't say they have heavily checkered comparment scores, whereas hypercompartmentalised phenotypes switch less and are as I see them heavily checkered. It would then seem as if we would have to incorporate a 'meaningful'-ness to the A/B switches.

A few rough ideas:
- Take the difference vector of compartment scores and correct that for the standard deviation / measure of spread of that difference vector.
- Take the observed / expected matrix for each arm, calculate for each row/column an autocorrelation based metric.

**Comment by robinweide** [comment]
Implemented in ATA-quant
