### ISSUE TITLE
APA for one loop fails

### ISSUE THREAD

**Issue by robinweide** [robinweide/GENOVA#159]
**Describe the bug**
When only giving one loop to APA, it fails.

**To Reproduce**

1.  APA(WT, bedpe = loops[1,])

```
Error in class(y) <- "matrix" : 
  invalid to set the class to matrix unless the dimension attribute is of length 2 (was 0)
```
**Expected behavior**
It should just do an APA and still give a matrix out. Maybe add another row with NA's?

**Comment by teunbrand** [comment]
Seems to be a bug due to the default `drop` argument in matrix subsetting, e.g.:

```
> m <- matrix(1:9, 3)
> class(m[1, ])
[1] "integer"
> class(m[1, , drop = FALSE])
[1] "matrix"
```

**Comment by teunbrand** [comment]
This should now be fixed for APA, and also pre-emptively for several other aggregation functions that could suffer from this.
