### ISSUE TITLE
splitJuicerData doesn't fill bins

### ISSUE THREAD

**Issue by teunbrand** [robinweide/GENOVA#165]
**Describe the bug**
Trying to load an experiment from an .hic file, but 50+ warnings were given. The traceback points to the `find_centromeres` function. However, on closer inspection, there were missing bins in the index.

This is a representative piece of the problem:

```
> index[4810:4820,]
    V1        V2        V3   V4
 1:  1 121350000 121375000 4810
 2:  1 121375000 121400000 4811
 3:  1 121425000 121450000 4812
 4:  1 121450000 121475000 4813
 5:  1 121475000 121500000 4814 # Before centromere
 6:  1 142525000 142550000 4815 # After centromere
 7:  1 142550000 142575000 4816
 8:  1 142575000 142600000 4817
 9:  1 142600000 142625000 4818
10:  1 142625000 142650000 4819
11:  1 142650000 142675000 4820
```

As you can see, the index does not contain centromere-bins, whereas I would have expected bins to be present in the index but absent in the matrix. This subsequently fails the assumption op the `find_centromeres` function that centromeres can be found in part by looking at missing bins in the matrix.

**Comment by teunbrand** [comment]
Should be fixed.

**Comment by asedenocacciatore** [comment]
Loading an experiment from .hic file still results in indexes where the bins are not similar across experiments. For example for two different experiments loaded both from .hic files with similar resolution the indexes are:
```
> expA$IDX
          V1        V2        V3     V4
     1: chr1    650000    660000      3
     2: chr1    660000    670000      4
     3: chr1    670000    680000      5
     4: chr1    680000    690000      6
     5: chr1    690000    700000      7
    ---                                
285138: chrX 154880000 154890000 285138
285139: chrX 154890000 154900000 285139
285140: chrX 154900000 154910000 285140
285141: chrX 154910000 154920000 285141
285142: chrX 154920000 154930000 285142

> expB$IDX
          V1        V2        V3     V4
     1: chr1    650000    660000      3
     2: chr1    660000    670000      4
     3: chr1    670000    680000      5
     4: chr1    680000    690000      6
     5: chr1    690000    700000      7
    ---                                
294749: chrX 154880000 154890000 294749
294750: chrX 154890000 154900000 294750
294751: chrX 154900000 154910000 294751
294752: chrX 154910000 154920000 294752
294753: chrX 154920000 154930000 294753
```
This later results in compatibility issues for these experiments. I also would have expected bins to be present in the index even if they are absent in the matrix; it would be nice to ensure this is the case from loading. 

If this not possible, perhaps I can overcome this particular issue re-indexing the contacts in the indexes and matrices to match after the set of experiments is loaded.

**Comment by robinweide** [comment]
This is really a problem out of our control. But what would be an option is to make new indexes based on the output of get_juicer_metadata(): chrom_name_length.

**Comment by teunbrand** [comment]
@asedenocacciatore you can now use `sync_indices()` in the dev branch.
