### ISSUE TITLE
Are saddle() output MAT$value(s) log2?

### ISSUE THREAD

**Issue by qiadu** [robinweide/GENOVA#167]
Hello, 

I am currently using GENOVA to produce saddle plots and to look at compartment strengths.
 
I notice in the 'visualise.compartmentStrength' function, the 'MAT$value' values are unlogged prior to calculating the average OE score for the top and bottom 20% of A/B compartment bins.

However, I cannot see where the 'MAT$value' values are initially "log2-ed" in R/saddleFunctions.R. I am using HiC-Pro iced.matrix and abs.bed as inputs. 

I might just be missing/misreading something. Please let me know. I do see where the values are "log2-ed" in R/notes/saddle_old (line # 373).

Thank you,
Qian

**Comment by robinweide** [comment]
Dear Qian,

They are not and this is a known bug of the old saddle-function. 

Please update to the latest version.

Best,
Robin
