### ISSUE TITLE
Missing logo on README

### ISSUE THREAD

**Issue by heytitle** [robinweide/GENOVA#170]
**Describe the bug**
It seems the logo's path in `README.md` is not correct.

<img width="922" alt="image" src="https://user-images.githubusercontent.com/1214890/71327877-5c81c600-250e-11ea-9fa1-c09fff1dc042.png">

**Comment by robinweide** [comment]
Thanks for your help! 

https://github.com/robinweide/GENOVA/commit/de6f77f0f42611550473c52a4e1607b3b2442854
