### ISSUE TITLE
cross-SCAn

### ISSUE THREAD

**Issue by robinweide** [robinweide/GENOVA#172]
- in: a (named) list of bed.df's
- out: the enrichment-score (for each exp and pair of df's)
- arguments: 
  -  method = ('lfc', 'diff')
  -  shift = 1e6
  -  min_distance = 2*res
  -  max_distance = 1e6

**Comment by teunbrand** [comment]
Is the name 2D-SCAn final? Because I don't find the 2D prefix very informative, as all matrix aggregations work with 2D locations. 
An alternative could be 'cross-SCAn/C-SCAn' after the SQL terminology 'cross-join' (and the PE-SCAn would in SQL terminology be a 'self-join').

**Comment by robinweide** [comment]
Not at all.
I like the cross-SCAn a lot. Let's make that the working title.

**Comment by teunbrand** [comment]
TODO:
- [ ] Set export tags again
- [ ] Anchor function
- [ ] CSCAn function
- [ ] Adjust `rep_mat_lookup`
- [ ] print method
- [ ] `visualise` method
- [ ] `plot` method
- [ ] `bundle` method
- [ ] `unbundle` method
- [ ] `quantify` method

**Comment by teunbrand** [comment]
All is implemented now.
