### ISSUE TITLE
Make error of check_compat_exp() informative

### ISSUE THREAD

**Issue by asedenocacciatore** [robinweide/GENOVA#173]
GENOVA gives a cryptic error when experiments in a `explist` are not compatible:
```
Error in vapply(seq_along(hic_10kb)[-1], function(i) { : 
  values must be type 'double',
 but FUN(X[[1]]) result is type 'character'
```
This is because `check_compat_exp()` uses a vapply that restricts `FUN.VALUE` to a logical, but when the IDX of the experiments differs the current comparison outputs "Different number of rows" rather than FALSE. 

This can be solved by wrapping this comparison within an `isTRUE()`, for instance.

**Comment by teunbrand** [comment]
Closing this, as this should be OK now with Angela's PR
