### ISSUE TITLE
size_bin/size_bp in ARA

### ISSUE THREAD

**Issue by deWitLab** [robinweide/GENOVA#176]
When I run ARA and the size_bp is set I get the following warning:
"Both 'size_bin' and 'size_bp' are set. Continuing with 'size_bin'."

This is awkward because it means having to manually set size_bin to NULL.

I would suggest setting both to NULL in the header and then set size_bin to 21 is both are NULL.

**Comment by teunbrand** [comment]
The easiest way is probably to adjust `parse_rel_pos()` to resolve the situation by using an internal default when both are `NULL` and then set the external defaults to `NULL` for both `size_bin` and `size_bp`.

**Comment by teunbrand** [comment]
Should be fixed
