### ISSUE TITLE
Show only top row in visualise

### ISSUE THREAD

**Issue by deWitLab** [robinweide/GENOVA#177]
See title. visualize now always plots two row. Especially in cases where there is only one Hi-C experiment this seems a bit overkill. The option to remove the differential row (bottom) would be great.

**Comment by robinweide** [comment]
The new workings of `visualise()` will be in the next update. When setting `metric` to `NULL`, the second row will be omitted. To overcome overhyping of the results, the default for multiple samples will be `lfc`.

So: 
- if only one contacts-objects is found in the discovery-object: metric = `NULL`
- if multiple contacts-objects are found in the discovery-object: metric = `"lfc"`

**Comment by teunbrand** [comment]
Fixed in 06cfad4866c2ddc145fe6ff0a6dafe9be0d915c8
