### ISSUE TITLE
vignette pdf missing

### ISSUE THREAD

**Issue by zxtzhangqian-float** [robinweide/GENOVA#178]
Hi, Robin
I still vignette pdf on the main page is missing. I wonder if you can upload it again for beginners:)
Xiaotian

**Comment by robinweide** [comment]
Dear Xiaotian,

Hete you go: github.com/robinweide/GENOVA/raw/dev/vignettes/GENOVA.pdf

Best,
Robin

https://github.com/robinweide/GENOVA/commit/05692c39fdf9b6ab4d00938db40fa61e842fad8a
