### ISSUE TITLE
insulation heatmap: dips

### ISSUE THREAD

**Issue by robinweide** [robinweide/GENOVA#179]
Users report that the profile-plots have unexpected dips in them. I suspect we're not omitting/handling _-Inf_-scores here. 

My suggestions:
-  set _-Inf_ values to the lowest found finite number per sample (short term)
- update `insulation_score()` so that it doesn't  get a chance to do `log(0)`  (long term)

**Comment by teunbrand** [comment]
@asedenocacciatore You had this problem too right? I can't reproduce what must have happened, do you have reprex for this bug?

**Comment by asedenocacciatore** [comment]
Using the same data I originally encountered this issue, it does not happen any more. So it seems solved now.
