### ISSUE TITLE
Precisely document output of analysis functions

### ISSUE THREAD

**Issue by teunbrand** [robinweide/GENOVA#186]
Now, the documentation of the e.g. saddle function states for the return value:

```
A saddle_discovery object.
```

Which is true, but quite useless if you want to dive into the output data itself.  It would probably be better if we document things precisely, i.e.:

```
A saddle_disovery object containing the following elements:

* saddle: A data.table object with following columns
  - exp: A character with the sample names from the explist argument
  - chrom: A character indicating the chromosome name and arm (p or q)
  - q1: An integer giving the first compartment score quantile bin. Lower numbers indicate smaller compartment scores.
  - q2: An integer giving the second quantile bin
  - mean: A numeric with the average observed over expected value at the indicated quantile bins
```

**Comment by robinweide** [comment]
I see this as not urgent and (at best) a bit important: let's spend our time on more pressing issues.
![image](https://user-images.githubusercontent.com/7115143/79440977-f2b68c00-7fd6-11ea-908e-e0405f0c8a3a.png)

**Comment by teunbrand** [comment]
Let's close this for now and reopen when we're working on this
