### ISSUE TITLE
Tibble acceptance in GENOVA

### ISSUE THREAD

**Issue by MarijneMia** [robinweide/GENOVA#188]
Some functions do not do well with tibbles as input, supposedly because the subsetting with df[1:3, 1] and tbl[1:3, 1] does not give the same output. I'll list the functions that appear to have this problem:  

- inter_intra_TAD.R,  res <- res[tad_bed[x, 1] == tad_bed[y, 1]]

**Comment by teunbrand** [comment]
@MarijneMia have you found any more since then?

**Comment by teunbrand** [comment]
I'm closing this for now, feel free to reopen when problems (re)surface.
