### ISSUE TITLE
Remove reshape2 dependencies

### ISSUE THREAD

**Issue by robinweide** [robinweide/GENOVA#189]
Since this is a depricated package, we should try to remove these (i.e. use the data.table alternative). @teunbrand is this something you can handle?

This will also stop warnings/errors like these:

```
> visualise(RCP_out, metric = 'lfc', contrast = 1)
Warning message:
In melt(out, id.vars = "distance") :
  The melt generic in data.table has been passed a data.frame and will attempt to redirect to the relevant reshape2 method; please note that reshape2 is deprecated, and this redirection is now deprecated as well. To continue using melt methods from reshape2 while both libraries are attached, e.g. melt.list, you can prepend the namespace like reshape2::melt(out). In the next version, this warning will become an error.
```

**Comment by teunbrand** [comment]
I'm gonna have a look at where we still use this, I think I removed them all in #110

**Comment by robinweide** [comment]
exactly. I found it just now in visualise.RCP. If I find more (by using GENOVA I'll add it here)

**Comment by teunbrand** [comment]
Probably best to replace all `melt`s with `melt.data.table` explicitly.

Reshape melts:

- [ ] https://github.com/robinweide/GENOVA/blob/35cb38a71ee4f38976dabe4e2d7b389d870b8c48/R/methods_quantify.R#L49
- [ ] https://github.com/robinweide/GENOVA/blob/08d4c9860c15c0d0062ce9868a38ce1b81563918/R/methods_discovery.R#L559

Data.table melts:

* https://github.com/robinweide/GENOVA/blob/08d4c9860c15c0d0062ce9868a38ce1b81563918/R/call_TAD_insulation.R#L57
* https://github.com/robinweide/GENOVA/blob/08d4c9860c15c0d0062ce9868a38ce1b81563918/R/insulation_heatmap.R#L99
* https://github.com/robinweide/GENOVA/blob/08d4c9860c15c0d0062ce9868a38ce1b81563918/R/methods_plot.R#L735
* https://github.com/robinweide/GENOVA/blob/08d4c9860c15c0d0062ce9868a38ce1b81563918/R/methods_plot.R#L852
* https://github.com/robinweide/GENOVA/blob/08d4c9860c15c0d0062ce9868a38ce1b81563918/R/methods_discovery.R#L559

**Comment by teunbrand** [comment]
As far as I know, all reshape2 dependencies are now gone
