### ISSUE TITLE
Announcement: new colourscales

### ISSUE THREAD

**Issue by robinweide** [robinweide/GENOVA#190]
I started updating the scales to bezier-corrected palettes (https://github.com/robinweide/GENOVA/commit/87f8ef8ed9eb94801f707bf63747dbc844acd434). I've now done hic.matrixplot() and this needs to be done to all functions that use gradients.

[Here is de script for the colours](https://github.com/robinweide/GENOVA/blob/master/R/colours.R)

```
inferno     -> bezier_corrected_hot
blue-red    -> bezier_corrected_divergent 
white-red   -> bezier_corrected_whiteRed 
ARA_diff    -> bezier_corrected_greenPink 
```

**Comment by teunbrand** [comment]
Would probably be most convenient then for the ggplot2 based functions to build a colour/fill scale out of this, no?

**Comment by robinweide** [comment]
Yes, will make those

**Comment by teunbrand** [comment]
I already made some for experimenting with the pyramid plot. I can share those if you'd like.

**Comment by teunbrand** [comment]
Checklist for functions that behoove colour updating
- [ ] `insulation_heatmap()`

**Comment by teunbrand** [comment]
Also, should we make the white/red versus hot choice a global option?

**Comment by teunbrand** [comment]
Should now work like this, showcasing both base R and ggplot based plots:

```
options("GENOVA.colour.palette" = "hot") # the default
hic.matrixplot(exp, chrom = "chr1", start = 30e6, end = 35e6)
pyramid(exp, chrom = "chr1", start = 30e6, end = 35e6)
```
![image](https://user-images.githubusercontent.com/49372158/82907985-9f394580-9f67-11ea-92a5-7c3ee1499be7.png)
![image](https://user-images.githubusercontent.com/49372158/82908034-b1b37f00-9f67-11ea-9415-ab9670615232.png)

```
options("GENOVA.colour.palette" = "whitered")
hic.matrixplot(exp, chrom = "chr1", start = 30e6, end = 35e6)
pyramid(exp, chrom = "chr1", start = 30e6, end = 35e6)
```

![image](https://user-images.githubusercontent.com/49372158/82908205-f212fd00-9f67-11ea-8e5b-ea4722df3be8.png)
![image](https://user-images.githubusercontent.com/49372158/82908254-00f9af80-9f68-11ea-8d0a-b4b44de39e32.png)

Also propagates to `visualise()`- and `plot()` methods for the linear scales (!= divergent)
Had to make a few changes to `hic.matrixplot()` wherein now `inferno = NULL` is the default (take from global options), but `TRUE` or `FALSE` still sets the 'hot' or 'whitered' scale.

**Comment by teunbrand** [comment]
Should be done propagating for all functions now.
