### ISSUE TITLE
Discovery class hierarchy

### ISSUE THREAD

**Issue by teunbrand** [robinweide/GENOVA#196]
To simplify writing methods for discovery objects, we could adopt a class hierarchy. This currently is already in place for APA, PESCAn, CSCAn, ATA, ARA etc. which have their own class, plus the `ARMLA_discovery` class. This made it super convenient to make e.g. `print()` and (`un`)`bundle()` methods for these. We could probably do the same for DI, compartment score and insulation score. Furthermore, it might be convenient to have a class for all discoveries just so that we might write general discovery methods that aren't dependent on how the discoveries are represented. This would mean that an APA returns an object of the 3 classes `APA_discovery`, `ARMLA_discovery` and `discovery`, but makes it easier to write methods for them.

**Comment by robinweide** [comment]
Good to think about these things. We have to look at it from the point of future-proofing: how much extra are we adding in the coming months? I feel that if the answer to this is "a little", this revamp will be only _nice to have_. If we feel that we will build a lot on top of these structures, then yes: this is definitely a good idea to implement.

**Comment by teunbrand** [comment]
Checklist for discovery classes
- [ ] APA
- [ ] PE-SCAn
- [ ] C-SCAn
- [ ] ATA
- [ ] ARA
- [ ] Virtual 4C
- [ ] Domainogram
- [ ] Insulation Score
- [ ] Compartment Score
- [ ] Saddle
- [ ] RCP
- [ ] Inter/intra TAD
- [ ] Directionality Index
- [ ] Chromosome Matrix

Generics that should have methods for this:
- [ ] `resolution()`
- [ ] `expnames()`
- [ ] `print()`
- [ ] `bundle()`
- [ ] `unbundle()`

**Comment by teunbrand** [comment]
Done
