### ISSUE TITLE
Usage question

### ISSUE THREAD

**Issue by Max-Highsmith** [robinweide/GENOVA#201]
I am having some difficulty using your tool and was hoping you might be able to help me understand its proper application.

In the GENOVA/R/PESCAN.R there is a function PESACn_covert, which expects two parameters: 'experiment' and 'bed'

my understanding is that 'experiment' should be the hic experiment and 'bed' is the peak bed file output from peak calling chip-seq data.

I used the GENOVA/scripts/juicerToGenova.py to generate  'out.sig' and 'out.bed' from a juicer hic file which has worked properly in other stages of my analysis. 

My peak bed file comes from the output of MACS2 peak calling.  I have tried running the PE_SCAN tool with the full ChIP-seq peak file (test_peaks.narrowPeak) as well as a smaller version of the peak file containing only the first 5000 lines (small_peak.bed)

my R script is currently:

experiment_0 <- construct.experiment("out.sig", "out.bed", "Day_0")
the_bed      <- read.table("small_peak.bed")#<- read.table("test_peaks.narrowPeak")
pesc_out     <- PESCAn_covert(experiment_0, the_bed)

However, the PESCAn_covert step does not complete even after running for 2 days using the small_peak.bed file.  Because the full 'test_peaks.narrowPeak' the file is considerably larger than 'small_peak.bed' (15MB vs 350Kb) and my hope was to apply this analysis to multiple HIC and Chip data sets I assume there is a user error on my part somewhere.

Essentially my questions are:
 1. What is the expected runtime for a PE_SCAN analysis on human data
2. Is there something I am fundamentally missing about the use of this tool

Thank you very much for your help.
Max

**Comment by robinweide** [comment]
Hi Max,

I hope all is well. PE-SCAn has been updated considerably in the last months. However, 5000 is still not a small set and would result in an enormous amount of combinations. Please try with a newer version of GENOVA, a lower resolution (40 or even 100kb), and with a smaller set.

Feel free to reopen if there are still issues.

Best,
Robin
