### ISSUE TITLE
NA in bed data.frame in ATA throws an error

### ISSUE THREAD

**Issue by deWitLab** [robinweide/GENOVA#202]
If I run ATA with a bed dataset with NAs in there I get the following error message:

`Error in if (sum(keep) < 1) { : missing value where TRUE/FALSE needed`

Maybe we can do some error handling here.

**Comment by teunbrand** [comment]
Just a note; we'd catch ~90% of these cases if we'd put this NA-check in `bed2idx()`.

**Comment by teunbrand** [comment]
It now signals more clearly that there are NAs.
