### ISSUE TITLE
also return individual regions in ARA/PESCan, like APA

### ISSUE THREAD

**Issue by robinweide** [robinweide/GENOVA#206]
Would be nice

**Comment by teunbrand** [comment]
Is this a suggestion to change the defaults? Because if you use `raw = TRUE`, you also get the `signal_raw` and `shifted_raw` lists with an array per sample.

**Comment by robinweide** [comment]
Yes, I guess that there isn't a reason to not add the raw data. Or do you think that this is too much of a memory-hog?

**Comment by teunbrand** [comment]
I'm fine with changing this, I have no strong feeling one way or the other.

**Comment by teunbrand** [comment]
The defaults are now to return the raw data too
