### ISSUE TITLE
Older functions: are they still used?

### ISSUE THREAD

**Issue by teunbrand** [robinweide/GENOVA#207]
I noticed that there are a number of functions that I never used and don't know if they are still used by people / in analysis. We might consider purging functions that have been superceded by others or are never used.

`shuffleHiC()` in shuffleHiC.R
- [x] Active
- [ ] Deprecate

`badBin.find()` in badBin.find.R
- [ ] Active
- [x] Deprecate

`badBin.plot()` in badBin.plot.R
- [ ] Active
- [x] Deprecate

`read_bedpe()` in read.bedpe.R
- [x] Active --> Should export?
- [ ] Deprecate

`rescale()` in rescale.R
- [ ] Active
- [x] Deprecate

`resize_mat()` in resize.mat.R
- [ ] Active
- [x] Deprecate

`differential.TAD.dotplot()` in differential.TAD.scatterplot.R
- [ ] Active
- [x] Deprecate (superseded by IIT_discovery visualise?)

`frequency.from.matrix()` in frequency.from.matrix.R
- [ ] Active --> Should export?
- [x] Deprecate (superseded by `pyramid()`?)

`chrom.comparison.plot()` in plot.chrom.comparison.R
- [ ] Active
- [x] Deprecate (superseded by `visualise.chrommat_discovery()?`)

Then there are probably also (sets of ) functions that could use an update:

- `cis_trans()` clearer documentation / unloop global parameters
- `centromere.telomere.analysis()` bring into discovery context
- `HiCseg.callTAD()` check whether it still works with updated contacts
- eigen_plot.R should we switch to `subset_contacts()` -> `compartment_score()` workflow?
- insulation_functions.R should we switch to `subset_contacts()` -> `insulation_score()` workflow?

**Comment by robinweide** [comment]
Good point. I made a choice for every function.
Next: 

- [ ] Deprecate or Activate above choices

**Comment by teunbrand** [comment]
Check!
