### ISSUE TITLE
pyramid

### ISSUE THREAD

**Issue by robinweide** [robinweide/GENOVA#211]
I cannot seem to set the crop_y (nothing changes), not can I show the y-axis. Also an option to set the colour-limits is missing.

**Comment by teunbrand** [comment]
`crop_y` should be a length 2 integer vector in basepairs of where to crop along the unrotated diagonal in distance space. e.g. `c(0, 20e6)` crops the pyramid to the diagonal up to contacts 20Mb away.

`display_yaxis = TRUE` shows the y axis

Colour limits can be set through `colour_scale = scale_fill_GENOVA(limits = c(0, 1000))`, so people can still choose square root and log transforms for their colours.

Try the following:
```
pyramid(exp, "chr1", 10e6, 20e6,
        crop_y = c(0, 5e6),
        display_yaxis = TRUE,
        colour_scale = scale_fill_GENOVA(limits = c(0, 1000)))
```

**Comment by robinweide** [comment]
Yes. This is exactly what I tried yesterday. The only difference is that I was using Z-normalised maps.

```
pyramid(exp_40kb, chrom = 'chr3', start = 30e6, end = 40e6, 
        display_yaxis = T, crop_y = c(0,4e6))

pyramid(exp_20kb_Z, chrom = 'chr3', start = 30e6, end = 40e6, 
        display_yaxis = T, crop_y = c(0,4e6))
```
The first works nicely, but the second just gives me a triangle.

![image](https://user-images.githubusercontent.com/7115143/83724404-848a5f00-a640-11ea-8bde-8144768a7806.png)

**Comment by teunbrand** [comment]
Ah ok that z-score thing gave me an important hint, I think I forgot to forward the `...` arguments to downstream functions, so hopefully this is an easy fix. (Famous last words)

**Comment by teunbrand** [comment]
Should be fixed
