### ISSUE TITLE
Compartment score signing using reference compartment scores

### ISSUE THREAD

**Issue by teunbrand** [robinweide/GENOVA#216]
It might be neat to implement a `ref` argument for the `sign_compartmentscore()` function that takes a compartment score discovery object with 1 sample as input and flips the signs of compartment scores such that they correlate with the reference.

The idea is that this works just like providing the `bedgraph` argument, but automates the data wrangling part of converting the discovery object to a bedgraph format, as a convenience for users. Maybe we could drop the requirement that the absolute correlation has to be more than >0.25 in this case.

Alternatively, if the discovery object to be signed contains compartment scores from multiple samples, we should be able to give an index or sample name to serve as reference.

My idea of how this then would work from a user perspective is then roughly as follows:
```
# Compute compartment scores for list of experiments
cs <- compartment_score(list(WT, KO))

# Sign the compartment score for a reference (WT)
ref <- sign_compartmentscore(unbundle(cs)[["WT"]], bed = H3K4me1)

# Use the reference to sign others
cs <- sign_compartmentscore(cs, ref = ref)
```

or do the following:

```
cs <- compartment_score(list(WT, KO), bed = H3K4me1, ref = "WT")
```

Which then only signs the WT with the `bed` argument, and then uses that as a reference for the `KO` sample.

**Comment by robinweide** [comment]
Hm, this still looks quite clunky. I would be happier with:

# Compute compartment scores for list of experiments
cs <- compartment_score(list(WT, KO), bed = H3K4me1)

# Use the reference to sign others
cs <- sign_compartmentscore(cs, ref =“WT")



> On 23 Jun 2020, at 11:42, Teun van den Brand <notifications@github.com> wrote:
> 
> 
> It might be neat to implement a ref argument for the sign_compartmentscore() function that takes a compartment score discovery object with 1 sample as input and flips the signs of compartment scores such that they correlate with the reference.
> 
> The idea is that this works just like providing the bedgraph argument, but automates the data wrangling part of converting the discovery object to a bedgraph format, as a convenience for users. Maybe we could drop the requirement that the absolute correlation has to be more than >0.25 in this case.
> 
> Alternatively, if the discovery object to be signed contains compartment scores from multiple samples, we should be able to give an index or sample name to serve as reference.
> 
> My idea of how this then would work from a user perspective is then roughly as follows:
> 
> # Compute compartment scores for list of experiments
> cs <- compartment_score(list(WT, KO))
> 
> # Sign the compartment score for a reference (WT)
> ref <- sign_compartmentscore(unbundle(cs)[["WT"]], bed = H3K4me1)
> 
> # Use the reference to sign others
> cs <- sign_compartmentscore(cs, ref = ref)
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

--------------------------------------------------------------------------------
Robin H. van der Weide
PhD-candidate  /  the Netherlands Cancer Institute
robinweide.github.io

**Comment by teunbrand** [comment]
This now happens automatically. You can revert back to old behaviour by setting `ref = NULL`.
