### ISSUE TITLE
Fork submission-version as V1 to dewitlab

### ISSUE THREAD

**Issue by robinweide** [robinweide/GENOVA#224]
github.com/dewitlab/GENOVA

**Comment by teunbrand** [comment]
Related to this, we should also package V1 up in a tarball and make a github release out of this. If we want to include the changes in current dev, we probably should re-knit the vignette as some functions have changed (e.g. `hic.matrixplot` -> `hic_matrixplot`).

**Comment by teunbrand** [comment]
This is now wrapped up as a tarball.
