### ISSUE TITLE
Generate O/E normalised matrix

### ISSUE THREAD

**Issue by QianzhaoJ** [robinweide/GENOVA#231]
Hi

  When comparing the interactions difference between different samples ,O/E normalization is a good choice. But I don't find a function to generate O/E normalised matrix in `GENOVA` directly . Could you give me some suggestions to generate the O/E matrix in `GENOVA` ?

Best,
Qianzhao

**Comment by teunbrand** [comment]
Hi there,

We do have the option to load in data as z-score normalised data, which also removes the distance-dependent trend so that samples can be compared without the distance trend.

However, if you want O/E matrices, I've sketched a function below that can help you calculate these:

```
library(data.table)

obsexp <- function(exp, location) {
  # Find indices
  location <- GENOVA:::standardise_location(location)
  start <- bed2idx(exp$IDX, location, "start")
  end   <- bed2idx(exp$IDX, location, "end")
  idx <- start:end
  
  # Get and normalise data
  data <- exp$MAT[CJ(V1 = idx, V2 = idx), nomatch = NULL]
  data[, D := V2 - V1]
  data <- data[, list(V1 = V1 - start + 1,
                      V2 = V2 - start + 1,
                      V3 = V3 / mean(V3)), by = D]
  
  # Format as matrix
  dim <- data[, max(c(V1, V2))]
  mat <- matrix(0, nrow = dim, ncol = dim)
  i <- as.matrix(data[, list(V1, V2)])
  mat[i] <- data$V3
  mat[i[, 2:1]] <- data$V3
  
  return(mat)
}

# Example
image(log2(obsexp(exp, "chr1:10e6-90e6")))
```

Best wishes,
Teun

**Comment by QianzhaoJ** [comment]
Hi,

Thanks for your reply , it would be very helpful !

Best,
Qianzhao
