### ISSUE TITLE
Support whole Chromosome for trans.compartment.plot

### ISSUE THREAD

**Issue by QianzhaoJ** [robinweide/GENOVA#232]
Hi :
  In `trans.compartment.plot`, users can choose which chromosome arm: 'p' or 'q' to draw. However, it seems like that don't   support for whole chromosome. I think whole chromosome would be very helpful to represent the difference in trans-interactions.

Best,
Qianzhao

**Comment by teunbrand** [comment]
Hi there,

I believe in the development branch there is a function called `trans_matrixplot()` that can plot arbitrary off-diagonal regions, including trans regions. It isn't limited to chromosome arms, but won't annotate the compartments. If you are interested in the difference between two experiments' trans-interactions, that might be the best fit.

Best wishes,
Teun

**Comment by teunbrand** [comment]
Since the `trans_matrixplot()` is now in the master branch, I'm closing this issue. I'm open to reopening if this isn't what you were looking for.
