### ISSUE TITLE
Holocentric centromere support

### ISSUE THREAD

**Issue by meisterpeter** [robinweide/GENOVA#241]
Some species (C. elegans, B. mori for example) have no centromere, but distributed attachment of microtubules along the entire chromosome. Some of the functions require definition of centromeric location. How can holocentric chromosomes be handled?

**Comment by teunbrand** [comment]
Just to make a list of functions I'm aware use centromere information, to  get an idea of the scope:
* `compartment_score()`
* `centromere.telomere.analysis()`
* `compartment_matrixplot()`
* `find_centromeres()`
Probably for `compartment_score()` and `compartment_matrixplot()` it'd make sense to offer centromere-free alternatives.

**Comment by meisterpeter** [comment]
I guess the most important ones are 
`compartment_score()`
`compartment_matrixplot()` as the last two are for species with centromeres.

**Comment by robinweide** [comment]
We are planning to add an option to skip centromere-estimation during loading. This will be seen by the mentioned tools as having a centromere at chromosomal position `-1` and will then force whole-chromosome computations.

Expect this to be done and ready in a day or two.

Thanks for your input: you're making GENOVA better for everybody :+1:

**Comment by teunbrand** [comment]
You can now set `centromeres = FALSE` in `load_contacts()` to signal that the data doesn't contain centromeres. The `compartment_score()` function then uses whole chromosomes instead of arms.
