### ISSUE TITLE
Cooler balancing creates issue with insulation-score [needs reprex]

### ISSUE THREAD

**Issue by robinweide** [robinweide/GENOVA#242]
Additionally, is there a reason why the insulation score function would work with the non normalized matrix (`balancing = F`) but not with the balanced one (`balancing = T`). Balancing was done with `cooler balance`
Raw counts: 
![image](https://user-images.githubusercontent.com/46744165/105905440-ba8eb000-6022-11eb-861e-5c04eb0397f7.png)
Balanced 
![image](https://user-images.githubusercontent.com/46744165/105905515-d09c7080-6022-11eb-9a4a-7cfa53b1a0fc.png)

_Originally posted by @meisterpeter in https://github.com/robinweide/GENOVA/issues/240#issuecomment-767828240_

**Comment by robinweide** [comment]
As said in title, I will help us tremendously if you can provide some test-data and -code to reproduce this error. Send me a message on twitter, etc. if you do not want to post it here.

**Comment by robinweide** [comment]
It could very well be that your issue is now solved due to https://github.com/robinweide/GENOVA/commit/bc157479ebab8cd1384799a4ac14c10203475f1b

This patch enables the transfer from KR to the weights-column inside the cooler-datastructure. 

![image](https://user-images.githubusercontent.com/7115143/105980549-4b9e6f00-6095-11eb-875b-6b96a015d66f.png)

Please try it out on the dev-channel,  @meisterpeter

**Comment by robinweide** [comment]
Update: the issue came from a malformed weight-column in the cooler-file (which included unexpected `nan`). 
This is now fixed in https://github.com/robinweide/GENOVA/commit/8dd53de17dc1e85096a813e297343ba0f80e9248.

Closing this because the issue is resolved.

**Comment by mdozmorov** [comment]
It appears balancing remains an issue. This:
```r
experiment1 <- load_contacts(signal_path = fileNamehic, sample_name = "exp1", resolution = 10000, balancing = TRUE, colour = "red", centromeres = centromeres)  

chr=2
experiment1$MAT[experiment1$MAT$V2 %in% experiment1$IDX$V4[experiment1$IDX$V1 == chr] |
                experiment1$MAT$V3 %in% experiment1$IDX$V4[experiment1$IDX$V1 == chr], ]
```
gives `Empty data.table (0 rows and 3 cols): V1,V2,V3`. Consequently, insulation scores are not calculated. With unbalanced data (`balancing = FALSE`), the data looks as on other chromosomes, and the dynamic range of interaction frequencies is similar.

This happens only on one chromosome and only in one experiment. Using either `.hic` or `.mcool` files. The other experiments, processed with the same technology and pipelines, work fine with `balancing = TRUE`. This is as far as I can reasonably debug it. Is there anything else to try?

**Comment by teunbrand** [comment]
Hello there,

> This happens only on one chromosome and only in one experiment.

That sounds like a rare case then that would be difficult to debug without the specific dataset that causes the bug. Are you willing to share some data that can reproduce this issue?

**Comment by mdozmorov** [comment]
I can share the data, privately. The simplest would be to share the full file via our university's Google drive. If you provide your e-mail, I'll do that, or, if you have other suggestions, please, let me know.

**Comment by teunbrand** [comment]
Yes that would work, my email is in the description file of this repository:

https://github.com/robinweide/GENOVA/blob/d158e99979a2989d431ee497299ba4263fd2ac70/DESCRIPTION#L6

**Comment by mdozmorov** [comment]
Hi Teun, did you have a chance to check the file? I would prefer to stick with GENOVA TADs but cannot since we have the failing chromosome.

**Comment by teunbrand** [comment]
I think there might be missing values in the balancing vector. These result in NaNs in the import, which GENOVA throws out because they're useless for computing anything with.

As a result, `experiment1$IDX$V1 == chr` from you code all evaluate to `FALSE` leaving you with a 0-row data.table. I'm going to suggest to figure out the root cause of the missing values in the balancing vector, or simply use the 25kb resolution instead (which seems to import just fine).

``` r
# Import balanced chr2 --> Missing values
imp <- strawr::straw("KR", file, "2", "2", unit = "BP", 10e3)
head(imp)
#>       x     y counts
#> 1 10000 10000    NaN
#> 2 10000 20000    NaN
#> 3 20000 20000    NaN
#> 4 10000 30000    NaN
#> 5 20000 30000    NaN
#> 6 30000 30000    NaN

# Import balanced chr3 --> This is fine
imp <- strawr::straw("KR", file, "3", "3", unit = "BP", 10e3)
head(imp)
#>       x     y    counts
#> 1 10000 10000 581.14752
#> 2 10000 20000 121.18054
#> 3 20000 20000 421.71722
#> 4 10000 30000  43.06493
#> 5 20000 30000  91.16332
#> 6 30000 30000 408.23642

# Import raw chr2 --> This is fine
imp <- strawr::straw("NONE", file, "2", "2", unit = "BP", 10e3)
head(imp)
#>       x     y counts
#> 1 10000 10000    353
#> 2 10000 20000     63
#> 3 20000 20000    486
#> 4 10000 30000     27
#> 5 20000 30000    129
#> 6 30000 30000    501
```
