### ISSUE TITLE
Error in loading mcool files and visualize compatment

### ISSUE THREAD

**Issue by chenggang108** [robinweide/GENOVA#249]
Dear @deWitLab 

Thank you for developing such a wonderful tool. I am running some tests but run into some issues. I am appreciated that you can help with them.
First question:  It shows error when I import mcool files as input. It does works when I set resolution as 10000, 25000, 50000 even 250000, but shows error when the resolution are 100000, 500000, 1000000
 Here is how it looks: 
 ```
> mES_100K <- load_contacts(signal_path = '/data/chengg2/MicroC_mES/coolfiles/1000/ESC_WT30-31.200bpFiltered.mcool', sample_name = "mES", resolution = 100000, balancing = 'T', colour = "green")
Reading data...
Error in rhdf5::h5read(file = cooler, name = paste0("/resolutions/", resolution,  : 
  Object '/resolutions/1e+05/bins' does not exist in this HDF5 file.
```

My mcool file should be Ok, it has been used for other analysis, Below is the list of this mcool file
```
cooler ls ./MicroC_mES/coolfiles/1000/ESC_WT30-31.200bpFiltered.mcool
./MicroC_mES/coolfiles/1000/ESC_WT30-31.200bpFiltered.mcool::/resolutions/1000
./MicroC_mES/coolfiles/1000/ESC_WT30-31.200bpFiltered.mcool::/resolutions/2000
./MicroC_mES/coolfiles/1000/ESC_WT30-31.200bpFiltered.mcool::/resolutions/5000
./MicroC_mES/coolfiles/1000/ESC_WT30-31.200bpFiltered.mcool::/resolutions/10000
./MicroC_mES/coolfiles/1000/ESC_WT30-31.200bpFiltered.mcool::/resolutions/25000
./MicroC_mES/coolfiles/1000/ESC_WT30-31.200bpFiltered.mcool::/resolutions/50000
./MicroC_mES/coolfiles/1000/ESC_WT30-31.200bpFiltered.mcool::/resolutions/100000
./MicroC_mES/coolfiles/1000/ESC_WT30-31.200bpFiltered.mcool::/resolutions/250000
./MicroC_mES/coolfiles/1000/ESC_WT30-31.200bpFiltered.mcool::/resolutions/500000
./MicroC_mES/coolfiles/1000/ESC_WT30-31.200bpFiltered.mcool::/resolutions/1000000
./MicroC_mES/coolfiles/1000/ESC_WT30-31.200bpFiltered.mcool::/resolutions/2500000
./MicroC_mES/coolfiles/1000/ESC_WT30-31.200bpFiltered.mcool::/resolutions/5000000
./MicroC_mES/coolfiles/1000/ESC_WT30-31.200bpFiltered.mcool::/resolutions/10000000
```

It looks the resolution has to be labeled as 1e+0x

The second problem, It shows "Error: 'label_number' is not an exported object from 'namespace:scales'" when I visualize the compartment score.

Below are the command I 
> H3k4me3 = read.delim('./GENOVA_test/H3K4me3.peaks.bed', header = FALSE) 
> CS_out = compartment_score(list(mES_250K), bed = H3k4me3)
> visualise(CS_out, chr = "chr1")
**Error: 'label_number' is not an exported object from 'namespace:scales'**

Can you please help with this?

Thanks

Gang

**Comment by skelviper** [comment]
Hi Gang,
The first problem can be solve by run `options(scipen = 200)` before load your mcools file, I've mention this in #248

**Comment by teunbrand** [comment]
Hello there,

Thanks for reporting this issue and also thanks to @skelviper for providing the workaround. 
I've two comments at the time:
* With regards to the loading issue, we can definitely have a look into the number formatting.
* What is the version of the 'scales' package you're using? The `label_number()` function your error refers to is a recent-ish addition to that package and GENOVA depends on scales version >1.1.1.Solving this might be as simple as updating the scales package.

Best wishes

**Comment by teunbrand** [comment]
Hello,

I think I might have fixed the cooler resolution issue. Feel free to use the dev version and check if it has resolved the error.
With regards to the 'scales' error, could you let me know if updating the scales package resolved the issue?
Thanks!

Best wishes

**Comment by chenggang108** [comment]
Hi @teunbrand 

Both problems have been solved.

Thanks

**Comment by teunbrand** [comment]
Great, thanks for the report!
