### ISSUE TITLE
Using rtracklayer for tracks

### ISSUE THREAD

**Issue by robinweide** [robinweide/GENOVA#252]
**Is your feature request related to a problem? Please describe.**
`Bigwrig` is deprecated and not usable on Windows machines. 

**Describe the solution you'd like**
Using the `rtracklayer` would allow easier import of bigwigs and bedgraphs. Furthermore, it is more in tune with bioconductor-users then `Bigwrig`.

**Describe alternatives you've considered**
Praying to the bioinformatics-gods, speaking to goats and even using Bing to find an alternative.

**Additional context**
N/A

**Comment by teunbrand** [comment]
Just a note to not forget; adjust `hic_matrixplot()` example in vignette

**Comment by meisterpeter** [comment]
Hi Teun & Robin, do you think you will be able to pull this soon?

**Comment by teunbrand** [comment]
Yes, this is on the dev branch now. Apologies I just forgot to merge the PR.

**Comment by meisterpeter** [comment]
Looks like there is a small issue here.
I tried to install the dev branch with `devtools::install_github("robinweide/GENOVA",` ref = 'dev')` and I get:

```
`Downloading GitHub repo robinweide/GENOVA@dev
Erreur : Failed to install 'GENOVA' from GitHub:
  Missing commas separating Remotes: 'bioc::release/rhdf5
   bioc::release/rtracklayer
   bioc::release/IRanges'`
```
Thanks!

**Comment by teunbrand** [comment]
Right, this type of error should have been caught by the CI before merging. I'll file a seperate issue.

**Comment by meisterpeter** [comment]
It's only in the `GENOVA/DESCRIPTION` file, where the commas are missing...

**Comment by teunbrand** [comment]
Yes the fix for the problem should be straightforward, it is just that we've setup a CI system that should check every PR for whether it doesn't break the package and it failed to do so (which is worrying to me).

**Comment by teunbrand** [comment]
Alright I think I may have fixed the comma issue
