### ISSUE TITLE
Compare contacts between two regions

### ISSUE THREAD

**Issue by chenggang108** [robinweide/GENOVA#254]
Hi @teunbrand 

I go through the GENOVA and found that most of the comparison is between two samples. I wonder whether this package can perform comparison between regions that I am interested in. For example, we are interested in double strand breaks. Can we compare the contact probability of between the regions the systematic introduced DSBs and random regions?

Thanks

**Comment by teunbrand** [comment]
Hi Chengang,

Are you interested in relative contact probabilities; the `RCP()` function? Robin put an example in the [vignette](https://github.com/robinweide/GENOVA/blob/master/vignettes/GENOVA_vignette.pdf) on page 10 where he compares regions under ChIP-seq peaks, which you could in theory substitute by regions where you've found DSBs. I don't think we specifically have random regions as control, but you could always shuffle the DSB locations randomly and use that, or compare the DSB regions to genome wide trends.

Best wishes

**Comment by chenggang108** [comment]
Hi Teun,

Thank you for your swift reply. I did see that part and perform RCP for regions of my interested and random regions. I am sorry that I did not make it clear enough. I wonder if this algorithm can something like "Figure 5: RCP in lfc-mode" for different regions.  Instead of log2(Psample/Pcontrast), but perform log2(regions of interested/random).  Is that interesting to do?

Thanks

**Comment by teunbrand** [comment]
Well we can sort-of do this, but we haven't setup the functions with this particular use case in mind, so it'll require some workaround. Example below:

``` r
library(GENOVA)

exp1 <- get_test_data("150k")

# Make some random bed regions of interest (roi) for example
idx <- exp1$IDX
i <- sample(c(TRUE, FALSE), nrow(idx), replace = TRUE)
roi <- as.data.frame(idx[i, 1:3])
not_roi <- as.data.frame(idx[!i, 1:3])

# Run RCP on both bed data.frames
rcp_roi <- RCP(exp1, bedlist = roi)
rcp_not_roi <- RCP(exp1, bedlist = not_roi)

# Change samplenames and colours
expnames(rcp_roi) <- "ROI"
expnames(rcp_not_roi) <- "Not ROI"
rcp_not_roi$raw$colour <- "tomato"
rcp_not_roi$smooth$colour <- "tomato"

# Combine and visualise
rcp <- bundle(rcp_roi, rcp_not_roi)
visualise(rcp, contrast = 2, metric = "lfc")
```

![](https://i.imgur.com/KHhzCYn.png)

<sup>Created on 2021-02-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by chenggang108** [comment]
Thanks, @teunbrand

**Comment by teunbrand** [comment]
I'll consider this resolved then.
