### ISSUE TITLE
hiç matrix colors

### ISSUE THREAD

**Issue by KunFang93** [robinweide/GENOVA#258]
Hi, 

I was wondering if it is possible to add color parameters in hic_matrixplot? For example, the red-white color. Thanks a lot!

Best,
Kun

**Comment by KunFang93** [comment]
Sorry, I somehow missed the colour parameters in load_contacts function.

**Comment by teunbrand** [comment]
The colour parameter in `load_contacts()` is for distinguishing one experiment from the next in primarily the `visualise()` functions that you can run on results. If you want to tweak the colours in e.g. `hic_matrixplot()` and other direct visualisation of Hi-C data, you can use `options("GENOVA.colour.palette" = ...)` as is documented in `?GENOVA_colours`.

Setting it to `"whitered"` is a keyword for a white-red scale.
``` r
library(GENOVA)

test <- get_test_data("40k", download = TRUE)

options("GENOVA.colour.palette" = "whitered")

hic_matrixplot(
  test, 
  chrom = "chr21", start = 40e6, end = 60e6,
  cut.off = 700
)
```

![](https://i.imgur.com/5gGaTNM.png)

But you can set a vector of colours manually as well.
``` r
options("GENOVA.colour.palette" = viridisLite::magma(12))

hic_matrixplot(
  test, 
  chrom = "chr21", start = 40e6, end = 60e6,
  cut.off = 700
)
```

![](https://i.imgur.com/S31FBfG.png)

<sup>Created on 2021-03-27 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by KunFang93** [comment]
Understand! Thanks for your explanation and exmaple!
