### ISSUE TITLE
Adjustable Color bar in hic_matrixplot 

### ISSUE THREAD

**Issue by KunFang93** [robinweide/GENOVA#260]
Hi, Teun

I was wondering if it is possible to add a colour_lim parameter (like colour_lim in trans_matrixplot) in the hic_matrixplot?  And I was also wondering if there is a way to show the color bar outside of the hic matrix? Thanks a lot!

Best,
Kun

**Comment by teunbrand** [comment]
Hello Kun,

Apologies for my late reaction. In the `hic_matrixplot()` function there is the `cut.off` option which serves a similar function as the upper bound on `colour_lim` in  `trans_matrixplot()`. I agree that, for consistency, it has value to also use `colour_lim` in `hic_matrixplot()`, but we haven't gotten around to this yet. At present, only `pyramid()`/`pyramid_difference()` produces colour bars automatically. 

Best,
Teun

**Comment by KunFang93** [comment]
Hi, Teun

Understand~ Thanks for your reply!

Best,
Kun

**Comment by teunbrand** [comment]
Hi Kun,

I've now added a `colour_bar` argument to the `*_matrixplot()` family of functions and changed the `cut.off` to `colour_lim` in the `hic_matrixplot()` function. Thanks for the suggestion!

Best,
Teun

**Comment by KunFang93** [comment]
Hi, Teun

Understand~ Thanks for your work!

Best,
Kun

**Comment by KunFang93** [comment]
Hi, Teun

I was wondering how to update the changes? I tried _remotes::install_github("robinweide/GENOVA")_ but R said "the SHA1 (774dc282) has not changed since last install". Thanks~

Best,
Kun

**Comment by teunbrand** [comment]
Hi Kun,

I've updated the dev branch. To install the dev branch you could run:
``` r
remotes::install_github("robinweide/GENOVA@dev")
```

Best.
Teim

**Comment by KunFang93** [comment]
Hi, Teim

Got it, thanks!

Best,
Kun
