### ISSUE TITLE
compartment_score - Error in if (any(newwidths > 2 * widths)) { : missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by YiweiNiu** [robinweide/GENOVA#262]
Hi,

Thanks for creating such a useful tool for Hi-C.

When using `compartment_score` function, I encountered the following error.

```R
> CS_out = compartment_score(hic_100k)
Error in if (any(newwidths > 2 * widths)) { : 
  missing value where TRUE/FALSE needed
```

I checked the code and found it was handling centromeres when throwing the error. Then I found the centromere regions loaded had `NA` values.

```R
> hic_100k[[1]]$CENTROMERES
    chrom start   end
 1:  chr1  3051  3124
 2: chr10  5880  5927
 3: chr11  9432  9516
 4: chr12 12078 12138
 5: chr13 14613 14664
 6: chr14 17624 17678
 7: chr15 20774 20840
 8: chr16 23856 23905
 9: chr17 25975 26070
10: chr18 28166 28301
11: chr19 30660 30727
12:  chr2 33888 33936
13: chr20    NA    NA
14: chr21    NA    NA
15: chr22    NA    NA
16:  chr3 38406 38478
17:  chr4 41380 41431
18:  chr5 45213 45302
19:  chr6 49310 49342
20:  chr7 53045 53129
21:  chr8 56328 56374
22:  chr9 59548 59601
23:  chrX 63045 63140
24:  chrY 66113 66119
    chrom start   end
```

The data I used were produced by HiC-Pro. Here are the command I used.

```R
library(GENOVA)

# centromeres
centromeres = read.delim('mm10.centromeres.bed',
                         sep = '\t',
                         header = FALSE,
                         stringsAsFactors = FALSE)
> centromeres
      V1        V2        V3
1   chr1 122026459 124932724
2  chr10  39686682  41593521
3  chr11  51078348  54425074
4  chr12  34769407  37185252
5  chr13  16000000  18051248
6  chr14  16000000  18173523
7  chr15  17083673  19725254
8  chr16  36311158  38265669
9  chr17  22813679  26616164
10 chr18  15460899  20861206
11 chr19  24498980  27190874
12  chr2  92188145  94090557
13 chr20  26436232  30038348
14 chr21  10864560  12915808
15 chr22  12954788  15054318
16  chr3  90772458  93655574
17  chr4  49712061  51743951
18  chr5  46485900  50059807
19  chr6  58553888  59829934
20  chr7  58169653  61528020
21  chr8  44033744  45877265
22  chr9  43389635  45518558
23  chrX  58605579  62412542
24  chrY  10316944  10544039

# samples
samples = c("LM0", "LM1")
# load in batch
hic_100k = lapply(samples, function(x) {
  load_contacts(
    signal_path = file.path(hicpro_out, x, 'iced/100000', paste0(x, '_100000_iced.matrix')),
    indices_path = file.path(hicpro_out, x, 'raw/100000', paste0(x, '_100000_abs.bed')),
    centromeres = centromeres,
    sample_name = x,
    colour = color_maps[x]
  )
})

> sessionInfo()
R version 4.0.3 (2020-10-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS release 6.6 (Final)

Matrix products: default
BLAS:   /usr/lib64/libblas.so.3.2.1
LAPACK: /usr/lib64/liblapack.so.3.2.1

locale:
 [1] LC_CTYPE=zh_CN.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=zh_CN.UTF-8        LC_COLLATE=zh_CN.UTF-8    
 [5] LC_MONETARY=zh_CN.UTF-8    LC_MESSAGES=zh_CN.UTF-8   
 [7] LC_PAPER=zh_CN.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=zh_CN.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] GENOVA_1.0.0

loaded via a namespace (and not attached):
[1] compiler_4.0.3    tools_4.0.3       data.table_1.14.0
```

And, it ran successfully when I did not use the centromeres in `load_contacts`.

Do you know how to solve this? Any help would be appreciated.

**Comment by YiweiNiu** [comment]
And the coordinates of centromeres input did not match with those in the GENOVA contact obj.

**Comment by teunbrand** [comment]
Hello there,

I couldn't help but notice the centromeres were taken from a file prefixed with `mm10` which typically indicates the mouse genome. The data.frame you read in includes chr20, chr21 and chr22, which are not part of the mouse genome (they have 19 autosomes). Because mouse centromeres are telomeric, there is generally no need to include exact centromere locations, so not using the `centromeres` argument would do the right thing. If you have human data, the problem might lie elsewhere and it would be great if we could replicate the problem with, for example, the test data (see `?get_test_data`).

For GENOVA, I think it is probably a good idea to warn about incompatible centromere data earlier on during data import or make more explicit where the problem lies.

Best,
Teun

**Comment by YiweiNiu** [comment]
Sorry, I was careless. I imputed  the hg38 centromeres.

**Comment by YiweiNiu** [comment]
Hi,

> Because mouse centromeres are telomeric, there is generally no need to include exact centromere locations, so not using the `centromeres` argument would do the right thing.

If not using `centromeres` argument, how the compartment strength is quantified by `quantify(saddle_out)`? It was said this was calculated for each chromosome arm.

The function `compartment_matrixplot` also need the `arm` parameter.

Bests,
Yiwei

**Comment by teunbrand** [comment]
Hello,

Internally, mouse chromosome arms are encoded as the p-arm of the chromosome, whereas the q-arm is missing. Effectively, this means that compartment scores and subsequent analyses treat whole chromosomes individually. In contrast, for human data, each arm is treated individually.

You can set `compartment_matrixplot(..., arm = "all")` if you want to plot the whole chromosome, though `arm = "p"` should probably also work.

Best,
Teun

**Comment by YiweiNiu** [comment]
Hi,

In function `compartment_matrixplot()`, it only works if I set the `arm` as `q`.

```r
> compartment_matrixplot(
+   exp1 = hic_100k[[1]],
+   #exp2 = hic_100k[[2]],
+   CS_discovery = CS_out,
+   chrom = "chr2", arm = "p", # actually whole chrom
+   colour_lim = c(0, 100)
+ )
Error in compartment_matrixplot(exp1 = hic_100k[[1]], CS_discovery = CS_out,  : 
  No `p` arm found. Try the other, or "all" option.
> compartment_matrixplot(
+   exp1 = hic_100k[[1]],
+   #exp2 = hic_100k[[2]],
+   CS_discovery = CS_out,
+   chrom = "chr2", arm = "all", # actually whole chrom
+   colour_lim = c(0, 100)
+ )
Error in if (zero_range(range)) zero_width else diff(range) : 
  missing value where TRUE/FALSE needed
```

Thank you very much for your quick reply.

**Comment by ziyi10** [comment]
> Hi,
> 
> In function `compartment_matrixplot()`, it only works if I set the `arm` as `q`.
> 
> ```r
> > compartment_matrixplot(
> +   exp1 = hic_100k[[1]],
> +   #exp2 = hic_100k[[2]],
> +   CS_discovery = CS_out,
> +   chrom = "chr2", arm = "p", # actually whole chrom
> +   colour_lim = c(0, 100)
> + )
> Error in compartment_matrixplot(exp1 = hic_100k[[1]], CS_discovery = CS_out,  : 
>   No `p` arm found. Try the other, or "all" option.
> > compartment_matrixplot(
> +   exp1 = hic_100k[[1]],
> +   #exp2 = hic_100k[[2]],
> +   CS_discovery = CS_out,
> +   chrom = "chr2", arm = "all", # actually whole chrom
> +   colour_lim = c(0, 100)
> + )
> Error in if (zero_range(range)) zero_width else diff(range) : 
>   missing value where TRUE/FALSE needed
> ```
> 
> Thank you very much for your quick reply.

Excuse me, have you solved it? I had the same problem.
