### ISSUE TITLE
How the difference is computed when 3 experiments are used in saddle function?

### ISSUE THREAD

**Issue by YiweiNiu** [robinweide/GENOVA#264]
Hi,

In the Figure 4C of your biorxiv paper, three experiments were compared. I wonder how the difference is computed in the `saddle` function.

Do you compare all the experiments with the **first one** in the `explist`? I just want to make sure.

**Comment by teunbrand** [comment]
Hello,

Yes the default behaviour of `visualise()` for the output of the `saddle` function is to take the first one as the reference. You can control which one is used as the reference by using the `contrast` argument in `visualise()`.

**Comment by YiweiNiu** [comment]
Thank you for your quick reply. Got it now.
