### ISSUE TITLE
How to plot the all-chromosome matrix?

### ISSUE THREAD

**Issue by Elphege-Nora** [robinweide/GENOVA#267]
**Is your feature request related to a problem? Please describe.**
I would love to reproduce the all-chromosome matrix in vignette figure 3 - would you be kind enough to share the code you have used there?

**Additional context**
Thank you so much for this package, this is such great work I am having so much fun with this!

**Comment by teunbrand** [comment]
Hello Elphege,

The code used to produce the vignette is in the vignettes/GENOVA.Rmd file. Specifically, the piece of code for the chromsome matrix can be found below: https://github.com/robinweide/GENOVA/blob/774dc282fc65d1ff61769ba6bc6f6a701403e54d/vignettes/GENOVA.Rmd#L197-L206

I don't recall the reason we've set the code chunk to `echo = F`, which masks the code chunk in the pdf output (we even put comments in there to help understand the function).  However, you can lookup any code used in the vignette in the .Rmd file.

Best,
Teun

**Comment by teunbrand** [comment]
I'm going to consider this closed for now and wil reopen if additional problems related to this issue pop up.
