### ISSUE TITLE
strand aware ARA

### ISSUE THREAD

**Issue by fgualdr** [robinweide/GENOVA#268]
Hi,

I am trying to use GENOVA to plot contact differences between samples. 
In particular I am interested to plot aggregated contacts occurring at promoters using ARA.
Is it possible to use the strand of the promoter BED position to flip the contacts accordingly so to make all with same directionality?

Thanks

Francesco

**Comment by teunbrand** [comment]
Hello,

Yes you can do this by using `anchors_ARA()`:

``` r
anchors <- anchors_ARA(exp$IDX, bed)
ara <- ARA(exp, anchors = anchors)
```
The strand is then encoded in an attribute `attr(anchors, "dir")`. Currently, we don't directly support a `strand` column, but assume reverse strand when `start > end`, which is noted in the 'ARA anchors' section of `?anchors`.

Best,
Teun

**Comment by teunbrand** [comment]
In the latest dev version I've added a `strand` argument to ARA, so it should now be more convenient to use the strand awareness.
