### ISSUE TITLE
Contrary results of RCP analysis and compartment strength

### ISSUE THREAD

**Issue by YiweiNiu** [robinweide/GENOVA#269]
Hi,

I am comparing three samples from mouse (mm10).

Compared to sample 1 (LM0), lower far-cis (10-100M) interaction was found for both LM1 and LM2, indicating weaker compartmentalisation.

![image](https://user-images.githubusercontent.com/25263399/121206242-e3fdf900-c8aa-11eb-9943-9a290c36446f.png)

But when quantifying the compartment strength after saddle analysis, I found contrary results. Compared to LM0, LM1 and LM2 showed higher compartment strength. The p values were computed by paired t-test.

![image](https://user-images.githubusercontent.com/25263399/121207401-d39a4e00-c8ab-11eb-83e4-5a3dec9504a2.png)

Do you have any ideas to explain this?

Sorry if the questions are too naive. I am new to this field.

Bests,
Yiwei

**Comment by teunbrand** [comment]
Hi there,

Compartment scores are calculated on the observed over expected (obs/exp) matrix, wherein expected is the average for every off-diagonal band. This obs/exp matrix thus implicitly straightens out the RCP, so I wouldn't expect a relation there. 
Compartment strength is a measure of how well A and B compartments are separated from oneanother, which is different than how many far-cis contacts are there. For your particular example, I think LM0 might have more far-cis contacts but these are more noisily distributed, compared to the fewer but more consistent far-cis contacts in LM1 or LM2. To confirm this, you can plot a few chromsome arms and see if the "checkerboard"-yness in LM1/LM2 is more evident.

Best,
Teun

**Comment by YiweiNiu** [comment]
Hi Teun,

Thank you for your helpful reply. I understand these results now. Thank you~
