### ISSUE TITLE
compartment_score　erro

### ISSUE THREAD

**Issue by liufuyan2016** [robinweide/GENOVA#277]
Dear professor,

I use the following command:
contro1 = compartment_score(Control_20Kb,bed = H3K4me3Peaks)

but an error is occured:

Error in `[.data.table`(IDX, , paste0(V1, ifelse(V4 < centros[.BY, start],  : 
  SETLENGTH() cannot be applied to an ALTVEC object.
Calls: compartment_score -> partition_chromosomes -> [ -> [.data.table

Could you help me? Thank you !

**Comment by teunbrand** [comment]
I'm closing this issue in favour of #278 which seems identical.
