### ISSUE TITLE
Problem in loading data

### ISSUE THREAD

**Issue by canfeng-HUA** [robinweide/GENOVA#283]
**Describe the bug**
I meet some problems when I load the data. Could you please help me fix it?

**To Reproduce**
```
WT_KB_matrix <- load_contacts(
+   signal_path = "./data/HI-C-WT-KB_27000_iced.matrix",
+   indices_path = "./data/HI-C-hrpL-KB_27000_abs.bed",
+   sample_name = "WT-KB",
+   resolution = 27000,
+   colour = "black")
```
> Reading data...
> Error in set(x, j = name, value = value) : 
>   Supplied 18005 items to be assigned to 18216 items of column 'C1'. If you wish to 'recycle' the RHS please use rep() to make this intent clear to readers of your code.

**Expected behavior**
No error. My data can be loaded in the package

**Screenshots**
![image](https://user-images.githubusercontent.com/71436402/141304197-9189fead-148d-4814-a5c6-3d65b6ba06bb.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacBook pro  iOS version 11.1 

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] MacBook pro 
 - OS: [e.g. iOS8.1] iOS version 11.1

**Comment by teunbrand** [comment]
Hi there,

Thank you for the report. 
Would you mind posting the head and tail (with n = 5 or so) of the `./data/HI-C-WT-KB_27000_iced.matrix` and `./data/HI-C-hrpL-KB_27000_abs.bed` files? The bug sounds akin to #276.

Best,
Teun

**Comment by canfeng-HUA** [comment]
Thanks a lot for your suggestion! I solve this problem. I add the title to the <.bed> file and solve this problem, following the suggestion from #276 

But I meet a new problem
![image](https://user-images.githubusercontent.com/71436402/141314015-5731d968-e3c9-4ac0-b367-042a65173679.png)

here is the head and tail of my bed files
![image](https://user-images.githubusercontent.com/71436402/141314080-0c91f0f1-877d-496c-9267-7d60b9318374.png)
