### ISSUE TITLE
Issue loading external compartment scores

### ISSUE THREAD

**Issue by batzza** [robinweide/GENOVA#284]
I am interested in using my own compartment calling rather than those generated by GENOVA. I have mostly been successful following the suggestions provided in https://github.com/robinweide/GENOVA/issues/273 

In brief, I do the following:
1. Load each of my 4 samples using load_contacts
2. Run compartment_score on the list of the 4 contacts
3. Read in my external compartment scores 
4. Join my compartment calls with the existing CS discovery object, replacing the old scores
5. Continue with downstream analysis

This all works fine except for Chr4 in my D090 sample. The issue appears to be in the original CS discovery object, GENOVA fails to call any compartment scores for all of chromosome 4 in this sample:
![image](https://user-images.githubusercontent.com/53917879/146572784-ef515073-c7fc-4f5b-ab1e-eae6db23f5b6.png)

However, I can successfully call scores externally. Here is the same region with my external scores added:
![image](https://user-images.githubusercontent.com/53917879/146572959-1733c8a5-3750-45ec-8ebb-4081f429f173.png)

The problem is that in all downstream analyses, chromosome 4 in D090 is treated as if it has no scores. For example, here is the Saddle plot of chromosome 4:
![image](https://user-images.githubusercontent.com/53917879/146573243-db59ccba-2eb4-44aa-bfc6-fa5ef8cebace.png)

I assume there is something in the CS object that marks these areas as missing so they are ignored in downstream analysis. How can I update this flag to reflect the external scoring?

**Comment by teunbrand** [comment]
The `compartment_score()` function keeps a run-length encoded partitioning of the chromosome arms in the `"partitioning"` attribute of the output.

``` r
library(GENOVA)

exp <- get_test_data("150k")

cs <- compartment_score(exp)
attr(cs, "partitioning")
#> Run Length Encoding
#>   lengths: int [1:4] 62 259 107 236
#>   values : chr [1:4] "chr21centro" "chr21q" "chr22centro" "chr22q"
```

<sup>Created on 2021-12-17 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

You could re-encode a partition, but I don't know if that'll help your case.
```
# Re-encoding the centromere of chr22 to p-arm
attr(cs, "partitioning")$value[3] <- c("chr22p")
```

**Comment by batzza** [comment]
Hm, that didn't seem to help. 

The root of my issue seems to be that the D090 chr4 compartment scoring fails so the downstream analyses exclude this entire chr4 in D090 even after I replace the compartment score value with my own values. 

As far as I can tell, the centromere regions are correctly encoded in my cs object.

**Comment by batzza** [comment]
Ah, I traced the error down -- my input mcool file had no contacts for chr4. GENOVA is working correctly, sorry for the confusion! Closing this issue now.

**Comment by batzza** [comment]
Unfortunately, I need to reopen this issue. I assumed my input file had no contacts on chr4 because the object created by GENOVA::load_contacts was missing chr4. Upon further inspection, my input file does have contacts for chr4 but GENOVA load_contacts fails to import them at the 50kb resolution. 

The behavior is very odd. if I load my file at 500kb resolution then all chromosomes are present, including chr4:

```
> ## Load data in GENOVA
> D090_500kb <- load_contacts(signal_path = "D090.hic",
+                            sample_name = "D090",
+                            balancing = T,
+                            centromeres = ucsc_centros,
+                            resolution = 5e5,
+                            colour = "red")
Reading data...
> D090_500kb$CHRS
 [1] "1"  "10" "11" "12" "13" "14" "15" "16" "17" "18" "19" "2"  "20" "21" "22"
[16] "3"  "4"  "5"  "6"  "7"  "8"  "9"  "M"  "X"  "Y" 
```
And I can check the bins of chr4 to see intra-chr contacts present:

```
> ## Glimpse data extract from chr4
> D090_500kb$IDX %>% filter(V1 == "4")
     V1        V2        V3   V4
  1:  4         0    500000 1381
  2:  4    500000   1000000 1382
  3:  4   1000000   1500000 1383
  4:  4   1500000   2000000 1384
  5:  4   2000000   2500000 1385
 ---                            
377:  4 188000000 188500000 1757
378:  4 188500000 189000000 1758
379:  4 189000000 189500000 1759
380:  4 189500000 190000000 1760
381:  4 190000000 190500000 1761
> D090_500kb$MAT %>% filter(V1 < 1761) %>% filter(V1 > 1381)%>% filter(V2 < 1761) %>% filter(V2 > 1381)
         V1   V2         V3
    1: 1382 1382 120815.182
    2: 1382 1383  32862.883
    3: 1382 1384  12429.883
    4: 1382 1385   4107.356
    5: 1382 1386   2548.044
   ---                     
70260: 1757 1758  19657.067
70261: 1757 1759  15901.068
70262: 1758 1758  75093.527
70263: 1758 1759  32155.825
70264: 1759 1759  76242.654
```

This process also works at 100kb resolution (not shown). However at 50kb resolution, all chromosomes EXCEPT chromosome 4 are loaded.

```
> D090_50kb <- load_contacts(signal_path = "Desktop/dunno/D090.hic",
+                             sample_name = "D090",
+                             balancing = T,
+                             centromeres = ucsc_centros,
+                             resolution = 5e4,
+                             colour = "red")
Reading data...
> D090_50kb$CHRS
 [1] "1"  "10" "11" "12" "13" "14" "15" "16" "17" "18" "19" "2"  "20" "21" "22"
[16] "3"  "5"  "6"  "7"  "8"  "9"  "M"  "X"  "Y" 
```

I'm fairly certain the chr4 is present and valid because I can successfully read chr4 from using strawr:

```
> data <- straw("NONE", "Desktop/dunno/D090.hic", "4", "4", "BP", 50000)
> head(data)
       x      y counts
1      0      0      4
2      0  50000     14
3  50000  50000    578
4      0 100000     14
5  50000 100000    575
6 100000 100000   1216
```
And I can visualize chr4 at 50kb in juicebox:
![image](https://user-images.githubusercontent.com/53917879/146661833-b0972dc4-2138-4d54-bcc5-9442ed3e33c7.png)

Any thoughts? Happy to share this hic file with you.

**Comment by batzza** [comment]
Unfortunately, I need to reopen this issue. I assumed my input file had no contacts on chr4 because the object created by GENOVA::load_contacts was missing chr4. Upon further inspection, my input file does have contacts for chr4 but GENOVA load_contacts fails to import them at the 50kb resolution. 

The behavior is very odd. if I load my file at 500kb resolution then all chromosomes are present, including chr4:

```
> ## Load data in GENOVA
> D090_500kb <- load_contacts(signal_path = "D090.hic",
+                            sample_name = "D090",
+                            balancing = T,
+                            centromeres = ucsc_centros,
+                            resolution = 5e5,
+                            colour = "red")
Reading data...
> D090_500kb$CHRS
 [1] "1"  "10" "11" "12" "13" "14" "15" "16" "17" "18" "19" "2"  "20" "21" "22"
[16] "3"  "4"  "5"  "6"  "7"  "8"  "9"  "M"  "X"  "Y" 
```
And I can check the bins of chr4 to see intra-chr contacts present:

```
> ## Glimpse data extract from chr4
> D090_500kb$IDX %>% filter(V1 == "4")
     V1        V2        V3   V4
  1:  4         0    500000 1381
  2:  4    500000   1000000 1382
  3:  4   1000000   1500000 1383
  4:  4   1500000   2000000 1384
  5:  4   2000000   2500000 1385
 ---                            
377:  4 188000000 188500000 1757
378:  4 188500000 189000000 1758
379:  4 189000000 189500000 1759
380:  4 189500000 190000000 1760
381:  4 190000000 190500000 1761
> D090_500kb$MAT %>% filter(V1 < 1761) %>% filter(V1 > 1381)%>% filter(V2 < 1761) %>% filter(V2 > 1381)
         V1   V2         V3
    1: 1382 1382 120815.182
    2: 1382 1383  32862.883
    3: 1382 1384  12429.883
    4: 1382 1385   4107.356
    5: 1382 1386   2548.044
   ---                     
70260: 1757 1758  19657.067
70261: 1757 1759  15901.068
70262: 1758 1758  75093.527
70263: 1758 1759  32155.825
70264: 1759 1759  76242.654
```

This process also works at 100kb resolution (not shown). However at 50kb resolution, all chromosomes EXCEPT chromosome 4 are loaded.

```
> D090_50kb <- load_contacts(signal_path = "Desktop/dunno/D090.hic",
+                             sample_name = "D090",
+                             balancing = T,
+                             centromeres = ucsc_centros,
+                             resolution = 5e4,
+                             colour = "red")
Reading data...
> D090_50kb$CHRS
 [1] "1"  "10" "11" "12" "13" "14" "15" "16" "17" "18" "19" "2"  "20" "21" "22"
[16] "3"  "5"  "6"  "7"  "8"  "9"  "M"  "X"  "Y" 
```

I'm fairly certain the chr4 is present and valid because I can successfully read chr4 from using strawr:

```
> data <- straw("NONE", "Desktop/dunno/D090.hic", "4", "4", "BP", 50000)
> head(data)
       x      y counts
1      0      0      4
2      0  50000     14
3  50000  50000    578
4      0 100000     14
5  50000 100000    575
6 100000 100000   1216
```
And I can visualize chr4 at 50kb in juicebox:
![image](https://user-images.githubusercontent.com/53917879/146661833-b0972dc4-2138-4d54-bcc5-9442ed3e33c7.png)

Any thoughts? Happy to share this hic file with you.

**Comment by teunbrand** [comment]
Could you check what the following line gives you?

``` r
head(strawr::straw("NONE", "D090.hic", "4", "4", "BP", 50000))
```

If there are NaNs in the 3rd column, this would suggest missing values in the balancing vector as was the case in https://github.com/robinweide/GENOVA/issues/242#issuecomment-1002621636.

**Comment by batzza** [comment]
Sure, thanks for the suggestion. That doesn't appear to be the issue here

```
> head(strawr::straw("NONE", "D090.hic", "4", "4", "BP", 50000))
       x      y counts
1      0      0      4
2      0  50000     14
3  50000  50000    578
4      0 100000     14
5  50000 100000    575
6 100000 100000   1216
```

Took it a step further and checked, appears to be no NaN's in the column:

```
> dim(is.na(data$counts))
NULL
```

**Comment by teunbrand** [comment]
I apologise I've asked for the wrong output. What I *meant* to ask for was the output of the following:

```
head(strawr::straw("KR", "D090.hic", "4", "4", "BP", 50000))
``` 

It was plain from your juicebox example that the raw data is there, but my worry was about the balanced data having missing pieces. What does juicebox display when you set the 'Norm' dropdown menu to a balanced normalisation?

**Comment by batzza** [comment]
Ah! You are correct:

```
> head(strawr::straw("KR", "D090.hic", "4", "4", "BP", 50000))
       x      y counts
1      0      0    NaN
2      0  50000    NaN
3  50000  50000    NaN
4      0 100000    NaN
5  50000 100000    NaN
6 100000 100000    NaN
```

The issue must be upstream of GENOVA, perhaps this particular chromosome is having some convergence issue. Thanks for the help troubleshooting this
