### ISSUE TITLE
How to get TAD boundaries from `call_TAD_insulation`

### ISSUE THREAD

**Issue by YiweiNiu** [robinweide/GENOVA#286]
Hi,

Sorry to bother again.

1. I wanted to check CTCF enrichment around TAD boundaries. But I do not know how to get TAD boundaries from the result of `call_TAD_insulation`.

```r
> head(TADcalls[[1]])
  chrom    start      end
1  chr1        0 16400000
2  chr1 16400000 17120000
3  chr1 17120000 24160000
4  chr1 24160000 33800000
5  chr1 33800000 34400000
6  chr1 34400000 34600000
```

The coordinates of this table were continuous. So the `end` column indicates TAD boundaries?

2. In the paper of GENOVA, figure 5c showed the intersections of TAD boundaries. How the "intersection" of two TAD boundaries was defined?

![图片](https://user-images.githubusercontent.com/25263399/147754606-235e6473-a282-4c41-8972-68d34e30b7be.png)

Thanks in advance.

Sorry if my questions are too obvious, I am still learning to analyze Hi-C data.

**Comment by teunbrand** [comment]
To get boundaries, you can take the `chrom`:`start` pairs and discard boundaries where `start == 0`. Robin made that figure, but I imagine it defined genomic ranges of 3 bins centered at TAD boundaries and he did intersection analysis on these ranges between samples.

**Comment by YiweiNiu** [comment]
Thank you for your reply. Got it now.
