### ISSUE TITLE
Insulation score visualisation

### ISSUE THREAD

**Issue by meisterpeter** [robinweide/GENOVA#289]
When visualising insulation score, x scale is doubled compared to the real size of the chromosomes (ie 17 Mb chromosome is >25 Mb long). Insulation score appears correctly (ie probably only a display error, not a calculation problem when calculating the insulation_score). Thanks for the great piece of software anyway!

**Comment by meisterpeter** [comment]
This is the "dev" branch

**Comment by teunbrand** [comment]
Yep, can confirm, silly mistake! Fix is underway on the dev branch.

Afterwards, should correctly plot the x-axis (example below pre-fix had north of 60Mb).

``` r
library(GENOVA)

exp <- get_test_data("40k")

ins <- insulation_score(exp)

visualise(ins, chr = "chr21")
```

![](https://i.imgur.com/xRprPSU.png)

<sup>Created on 2022-02-17 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
