### ISSUE TITLE
CSCAn -> visualise error

### ISSUE THREAD

**Issue by odovgusha** [robinweide/GENOVA#297]
**Describe the bug**
After running 
test = GENOVA::CSCAn(synched, bedlist = list(diff_atac_df[1:500,],all_ATAC_peaks[1:500,]))

I get 
Error in rep(5.5, length(unique(df$right)) - 1L) : 
  invalid 'times' argument
 
  after running 
  visualise(test)

Also, just wanted to ask a question about CScan function because I am a bit confused.
PE-scan aggregates all interaction signals between a set of regions.
For C-scan you need to provide at least 2 sets of regions. Doest it aggregates all the signals between two groups. i.e I have 5 promoters and 5 enhancers. Will C-scan look for the interaction signal of each promoter vs all the enhancers and then sum all the interactions of these promoters with enhancers?

Many thanks!

**Comment by teunbrand** [comment]
Thanks for reporting! I can indeed confirm that this error is thrown when 2 sets of regions are provided. Hoping to get a fix in soon.

C-Scan indeed looks for all locations where sets of regions might interact, within some distance (by default, a minimum of 50kb and maximum of 2Mb), and then aggregates this per set combination. It does not look for within-set interactions, that is what PE-Scan does.

**Comment by teunbrand** [comment]
Should be fixed now on dev branch :)

**Comment by odovgusha** [comment]
Many thanks! Sorry, could you suggest how to install the GENOVA from dev branch?

**Comment by teunbrand** [comment]
Sure, typically you can install from the dev branch in the following manner:
``` r
devtools::install_github("robinweide/GENOVA", ref = "dev")
```
