### ISSUE TITLE
Changing colors

### ISSUE THREAD

**Issue by sebastian-gregoricchio** [robinweide/GENOVA#298]
The tools in general are wonderful!

however there is only one tiny thing that would be nice to be implemented: the possibility to change the colors/colormap with custom colors. Indeed, in the matrixplot there are only two color scales available, while the aggregates have only the red/blue and/or purple/green colormaps. Similar for the pyramids.

There is already a way to change it manually that I perhaps am missing?
If not, it would be nice to implement it.  Such as low color, mid color, high color parameter for the aggregates and fold changes/differences. While provide other coloromaps for the pyramid/matrix.plot similar to those of python ([matplotlib colormap](https://matplotlib.org/stable/tutorials/colors/colormaps.html))

**Comment by teunbrand** [comment]
Broadly, colours of heatmaps can be changed by setting the `GENOVA.colour.palette` option.

``` r
library(GENOVA)

exp <- get_test_data("150k")

options("GENOVA.colour.palette" = c("white", "cyan", "blue", "black"))

hic_matrixplot(
  exp, chrom = "chr21", start = 20e6, end = 40e6
)
#> No colour limits were given: using 99% percentile: 7446.
```
![](https://i.imgur.com/ShvWDYv.png)

For ggplot2 output (e.g. the `visualise()` function) you can just override the fill scales. One tricky bit is that the divergent scale is controlled by the non-vanilla `altfill` aesthetic, so the scale's aesthetic and available aesthetics in the guide need to be adjusted.

```
# Just some dummy example. In general, call TADs at finer resolutions than 150k
tads <- call_TAD_insulation(insulation_score(exp))[[1]]
ata <- ATA(exp, tads)

dummy_ata <- ata
dummy_ata$signal <- dummy_ata$signal * runif(length(dummy_ata$signal))

ata <- bundle(ata, dummy_ata)

visualise(ata) +
  ggplot2::scale_fill_gradientn(
    colours = c("white", "gold", "darkorange", "black")
  ) +
  ggplot2::scale_colour_gradientn(
    aesthetics = "altfill",
    colours = c("white", "limegreen", "forestgreen", "black"),
    guide = ggplot2::guide_colourbar(available_aes = "altfill")
  )
#> Scale for 'fill' is already present. Adding another scale for 'fill', which
#> will replace the existing scale.
#> Scale for 'altfill' is already present. Adding another scale for 'altfill',
#> which will replace the existing scale.
```
![](https://i.imgur.com/1BdeylR.png)

<sup>Created on 2022-06-21 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by sebastian-gregoricchio** [comment]
Thank you very much for your reply!!!
