### ISSUE TITLE
Insulation score visualization problem

### ISSUE THREAD

**Issue by Moonriver1988** [robinweide/GENOVA#307]
Hello,

I am trying to plot the insulation score, and the x scale is incorrect, looks like the insulation score profile is correct, just the coordinates are wrong, the coordinates is around 30Mb larger than the coordinates I provide(e.g. provide "start = 57e6, end = 59e6", but in the plot is 87Mb to 89Mb), I tried to plot the whole chromosome, and the chromosome length is larger than its actual length, also larger around 30Mb.  Could you help me with this? Thank you very much!

**Comment by teunbrand** [comment]
Hi there,

Might this be related to #289, and if so, does it help to install the dev version?

Best,
Teun

**Comment by Moonriver1988** [comment]
Hello Teun,

Thanks for your reply! I checked #289, but I don't understand what is "the dev version", the dev version is the version on github and installed by "remotes::install_github("robinweide/GENOVA")"? I installed GENOVA in this way, and I am using GENOVA_1.0.0.9000.

**Comment by teunbrand** [comment]
You can install the dev version using the code below:

``` r
remotes::install_github("robinweide/GENOVA", ref = "dev")
```

**Comment by Moonriver1988** [comment]
It works after install dev version. Thank you very much for your help!
