### ISSUE TITLE
HiCPro sample format to be read by GENOVA?

### ISSUE THREAD

**Issue by pollicipes** [robinweide/GENOVA#310]
Hi!

I am trying to read my HiC matrix into GENOVA using the HiCPro format. I got my matrix from another program, and I want to format my matrix into a HiCPro format, but I can't get the `load_contacts` function to read my data. This is how both my *.matrix and *.bed files look:

![Screenshot 2022-10-13 at 14 50 51](https://user-images.githubusercontent.com/35963280/195607249-f9d21a68-0eae-4ded-9548-0597361d39b8.png)

My *.matrix contains only the full upper half of the matrix. They are tab-separated and have no header.

By the way, this is the error I get, in case it's useful:
```
Reading data...
Error in setkeyv(x, cols, verbose = verbose, physical = physical) : 
  some columns are not in the data.table: chrom
```
Would you mind to show an exact example for the file formats required for reading HiCPro files?

Thanks! :)
Best,
Juan

**Comment by teunbrand** [comment]
Yeah sure, the head of the `.matrix` file should look like the following, note that the 2nd column is the one that changes fastest:

```
1       1       3.555465
1       2       0.000000
1       59      36.985982
1       74      0.031127
1       78      0.028591
1       80      0.038704
1       84      0.027554
1       88      0.032006
1       91      0.033085
1       92      0.030852
```

And the head of the `.bed` file should look like this:

```
chrM    0       10000   1
chrM    10000   16571   2
chr1    0       10000   3
chr1    10000   20000   4
chr1    20000   30000   5
chr1    30000   40000   6
chr1    40000   50000   7
chr1    50000   60000   8
chr1    60000   70000   9
chr1    70000   80000   10
```

There are two differences I can point out for your examples, but I'm not sure if they're important (and if so, which one).
* Your `.bed` file is has 1-based start coordinates, whereas a typical bed file has 0-based start coordinates.
* Your `.matrix` file has unsorted index columns (the first two). The first column should vary the slowest and the second one the fastest.

If the program you used produces `.cool`, `.mcool` or `.hic` files, these should also be handleable in the `load_contacts()` function, so you might be able to circumvent reformatting entirely if that is the case.

Best,
Teun

**Comment by teunbrand** [comment]
Hi Juan,

Yes I can reproduce your error. The problem seems to be is that the automatic centromere finding utility seems to be fragile in this case where there are no apparent centromeres (which is probably a problem we should fix).

In the meanwhile, you example should work if you set `centromeres = FALSE`; e.g.:
```r
library(GENOVA)

bed_file <- "/path/to/test.bed"
mtx_file <- "/path/to/test.matrix"

exp <- load_contacts(
  signal_path  = mtx_file,
  indices_path = bed_file,
  sample_name  = "test", 
  centromeres  = FALSE
)

```

**Comment by teunbrand** [comment]
Alright the dev branch should have a fix for this particular issue now.

**Comment by pollicipes** [comment]
Oh, I see!
It works now! That was great, Teun.

In my case, this comes from chromosomes from a non-human species, so chromosomes may have a different architecture, with no centromeres in the middle-ish of the chromosome.

By the way, if I may... just a last quick question: I would like to run GENOVA stuff on individual chromosomes: 
Do you foresee any big trouble? In the vignette you recommend to read genome wide matrices, so I'm just curious if I can do this.

Big thanks, Teun!
Cheers,
Juan

**Comment by teunbrand** [comment]
In theory I don't foresee any problems with stuff that just considers the cis-contacts of chromosomes. It might be a problem for stuff like `chromosome_matrix()` or `trans_matrixplot()`. 

The only issue is that we don't have a one-chromosome-only variant of the `load_contacts()` function. However, seeing as you seem to be formatting data yourself, you might write out different chromosomes to different files.

Another thing is that you might want to do, is after you collected results from analyses, to combine them for the different chromosomes. At the moment there is no function to easily do this, but you could wrangle the data to do this.

Best,
Teun

**Comment by pollicipes** [comment]
Thanks for all Teun!
Best,
Juan
