### ISSUE TITLE
Issue reading in .hic (possibly due to juicer hic version 9)

### ISSUE THREAD

**Issue by tolender** [robinweide/GENOVA#332]
Hi,

I am trying to read in my .hic but it seems to be looking at the wrong column for the resolution info in the hic file. My .hic files are juicer v9, could this be a file version error?

WT.hic.juicer <- load_contacts(signal_path = 'data/WT.hic', sample_name = "WT", resolution = 10000, balancing = "KR")

Reading data...
Error in loadJuicer(juicerPath, resolution, scale_bp = scale_bp, scale_cis = scale_cis,  : 
  resolution is not found.
Available resolutions are -1828132276, 1077797004, -1074584380, -888507814, -770413841, 616882835, 130615830, -1458951954, -1491534451, 585037374, 1563262033, 1504091578, 1281046761, 178777955, 756390227, 1266036046, 591981132, 1021326707, 1683382740, 389355327, 1001312454, 1870000005, 959597790, -446819100, -917928723, 639998438, 1233722003, 31038428, 649763874, -442309899, 172776144, -1491045099, -1718662778, -1889323078, 485349702, -438765196, -643450053, 761503998, -1827775980, -1734448848, -1146869662, -1164177838, 1611381013, -1738082546, -195665714, -1070239385, 1401198677, 1117556947, 934829419, 490186924, -975688088, -747292567, 1164347815, -1725871681, 1233242284, -978626327, 1173440907, 647173491, -215694181, 1164333772, -555655660, -456741674, 978509208, -1269401482, -382680713, 1721173436, -835043161, 558517295, 616795795, 386365842, 1619367022, 606630261, 956211133, -1590434796, 1593416006, -457941939, -884617557, -1903035757, 50080201, 1

**Comment by teunbrand** [comment]
I've never seen a v9 .hic file before, do you happen to know of some publicly available sample data to test solutions with?

**Comment by tolender** [comment]
It is related to the Juicer v2.x update, as v9 hic files have slightly different formatting than previous hic files in Juicer v1.x .

https://github.com/aidenlab/juicer/wiki/FAQs
see Version issues (1.x vs 2.x)

**Comment by teunbrand** [comment]
Thanks for the link, I've assumed as much about the formatting. I don't know when I'll have time to debug this unfortunately.

**Comment by tolender** [comment]
Thanks for looking into it.

**Comment by teunbrand** [comment]
I'm going to keep this open as a reminder to look into it.

**Comment by teunbrand** [comment]
@tolender can I get you to try out the dev branch to see if this has solved the loading issue? You can install from the dev branch with `devtools::install_github("robinweide/GENOVA", ref = "dev")`

**Comment by tolender** [comment]
I installed the dev branch and I am now able to continue with the vignette, thank you so much!

**Comment by teunbrand** [comment]
Thanks for checking!
