### ISSUE TITLE
Juicer import calling centromeres well outside of chromosome size.

### ISSUE THREAD

**Issue by tolender** [robinweide/GENOVA#334]
- Imported contacts from Juicer .v9 and included mm10 centromeres bed. (all mouse chromosomes have centromeres from 0-3000000bp)

- Resulting object ignored supplied bed and called centromeres well outside of chromosome sizes, with zero values extending from end of actual chromosome data to the mis-calculated centromere 
(specifically from chr9 to chr19)

- Not sure if related but Juicer .hic has sort order chr1,2,3,4,5 etc. GENOVA object has sort order chr1,10,11,12 etc., or inter-chromosome matrices.

- Downstream analysis results in chromosome AB compartments being skewed and resulting saddle plots giving weird patterns.

- Also tried load_contacts_subset with specific regions per chromosome as a workaround but errors saying the feature has not been implemented for Juicer .hic
- Issue persists with all resolutions.
- Using centromeres=FALSE does not change the results
- Changing the centromeres to "chrom=1 start=1 end=1" in the dataframe afterwards doesn't fix it either.

Is there a temporary workaround I can use to remove the cells that are outside the bounds of the chromosomes from the dataframes?

WT.hic.40kb <- load_contacts(signal_path = 'data/WT.hic',
                                sample_name = "WT",
                                resolution = 40000, centromeres=mm10.centromeres,
                                balancing = 'KR',
                                colour = "black")

![image](https://github.com/robinweide/GENOVA/assets/112004074/435efde8-2f6d-48fe-96f3-9fe8ef45b5b7)

![image](https://github.com/robinweide/GENOVA/assets/112004074/9281cf71-a1b0-4210-8508-6c2c509c3b1b)

> WT.hic.40kb[["CENTROMERES"]]
    chrom start   end
 1:  chr1     1     1
 2: chr10  4809  4809
 3: chr11  9284  9284
 4: chr12 13759 13759
 5: chr13 18234 18234
 6: chr14 22709 22709
 7: chr15 27184 27184
 8: chr16 31659 31659
 9: chr17 36134 36134
10: chr18 40609 40609
11: chr19 45084 45084
12:  chr2 49559 49559
13:  chr3 54033 54033
14:  chr4 57956 57956
15:  chr5 61787 61787
16:  chr6 65506 65506
17:  chr7 69170 69170
18:  chr8 72729 72729
19:  chr9 75918 75918
20:  chrX 79106 79106

**Comment by teunbrand** [comment]
This sounds like an off-by-1 error somewhere but I've no way of debugging this problem as I don't have mouse mm10 v9 juicer files lying around.
