### ISSUE TITLE
load .hic file

### ISSUE THREAD

**Issue by AlcaArctica** [robinweide/GENOVA#340]
I wanted to try out this tool, but was unable to load my .hic file:
I tried:

```
Hap1_WT_10kb_juicer <- load_contacts(
  signal_path = 'hap1.hic',
  indices_path = NULL,
  resolution = 10000,
  sample_name = NULL,
  centromeres = NULL,
  colour = NULL,
  z_norm = FALSE,
  scale_bp = 1e+09,
  scale_cis = FALSE,
  balancing = TRUE,
  legacy = FALSE,
  verbose = TRUE
)
```

But I am getting the error:

```
Reading data...
Error in utils::combn(juicer_metadata[[1]]$chrom, m = 2) : n < m
```

Any ideas? I was successful in visualising the .hic file with juicebox, so the file itself seems to be okay.

**Comment by teunbrand** [comment]
Appears to be the case that only one chromosome was found in the metadata.
Have you tried the dev branch?

**Comment by AlcaArctica** [comment]
I installed the package with:
```
install.packages("remotes")
remotes::install_github("robinweide/GENOVA")
library(GENOVA)
```

**Comment by teunbrand** [comment]
You can install the dev version with `remotes::install_github("robinweide/GENOVA@dev")`.

**Comment by AlcaArctica** [comment]
Thanks. This solved the error!
