### ISSUE TITLE
APA differential analysis between two different sets of loops in one sample

### ISSUE THREAD

**Issue by Moonriver1988** [robinweide/GENOVA#345]
Hello,

I found the APA differential analysis is for analyze one set of loops in two different samples. I'd like to know how to do APA differential analysis for two different sets of loops in one sample, for example, compare CTCF anchored loop vs. non-CTCF loop strength in the same sample? Thank you!

**Comment by teunbrand** [comment]
I'd just run APA twice, once with each set of loops, use the `quantify()` function to summarise every loop in each result, then do a comparison of these summaries.

**Comment by Moonriver1988** [comment]
Thank you very much!
