### ISSUE TITLE
Can genova be applied to hichip data analysis?

### ISSUE THREAD

**Issue by YuZhang337** [robinweide/GENOVA#353]
Hi, @teunbrand

I am so sorry to bother you. I used Genova to analyze hic data before. Because it is in R language and can be run on a laptop, it is very convenient. Thank you for developing such a good software. 

Now I need to analyze hichip data and want to use the APA command to view the contact changes of a group of specific peaks. I would like to ask if Genova is suitable for hichip data analysis, especially if normalize is required when loading_contacts?

I'm looking forward to your guidance. Thanks.

Best,
Yu

**Comment by teunbrand** [comment]
Hi there,

I'm not sure, I never handled hichip data myself. 
I suppose if the file formats are the same, you can give it a go.
I'm afraid I don't have any advice to offer about normalisation.

Best,
Teun

**Comment by YuZhang337** [comment]
Thank you for such a quick reply
