### ISSUE TITLE
PESCAn Error: cannot allocate vector of size 150.9 Gb

### ISSUE THREAD

**Issue by YuZhang337** [robinweide/GENOVA#354]
Hi, @teunbrand

I am so sorry to bother you again. When I use the PESCAn function, I always encounter the problem of cannot allocating vector of size. Even if I adjust the number of peak beds to 2k, I still encounter such an error. Is PESCAn determined by the upper limit of the load matrix or bed? ? What do you recommend?

I'm looking forward to your guidance. Thanks.

Best,
Yu

**Comment by teunbrand** [comment]
The bed file affects this. If you have 10k peaks on a chromosome, it will try (10e3^2)/2= 5e7 combinations for that chromosome, so you quickly run out of memory this way. I'd recommend only taking the the top 5000 peaks or clustering nearby peaks, as it wasn't designed with raw peak calls in mind.

**Comment by YuZhang337** [comment]
OK, I understand, thank you very much.

**Comment by YuZhang337** [comment]
Hi, @teunbrand 

I have another question, although it has nothing to do with error reporting, but I will ask you under this issue, thank you.
I did an APA analysis and the results are as follows:
![image](https://github.com/robinweide/GENOVA/assets/70937959/a8a17f3c-4488-4f11-a7d1-36960c87fa8f)

My understanding is that the 3' upstream and 5' upstream of the loop interact more strongly in the mutant group than in the Ctrl group，and the interaction between loops also enhanced, right?

**Comment by teunbrand** [comment]
The dark feature in the bottom-left might be part of the diagonal, in which case it probably isn't too interesting with regards to looping. You should be able to set the minimum distance to get rid of the diagonal. Otherwise, yes, your mutant indeed has stronger loops.
