### ISSUE TITLE
Difference between input matrix value and GENOVA matrix object

### ISSUE THREAD

**Issue by Lucas446** [robinweide/GENOVA#356]
Hi, 

I have a question concerning the import of .cool HiC matrix (From HiCexplorer ConvertFormat .h5 to .cool, the .h5 has been normalized using KR). 

I realized that the load_contacts function of GENOVA is applying a factor (independent of the balancing option) to the data when comparing the values in $MAT$V4 and the value from the input,

Do you know where is this factor is coming from ?

Thanks a lot, 
Best, 
Tanguy

**Comment by robinweide** [comment]
Dear Tanguy,

This is a depth-normalization and can be stopped by setting `scale_bp = NULL`.

Best,
Robin

**Comment by Lucas446** [comment]
Perfect, it works great!
