### ISSUE TITLE
Error installing GENOVA with R versions > 4.0.0

### ISSUE THREAD

**Issue by MuhundenJ** [robinweide/GENOVA#366]
Hi Robin,

I am unable to install GENOVA with newer versions of R v4.4 (also 4.3, 4.0) on MacOS Sequoia 15.1.1. I get the following error message when I run `remotes::install_github("robinweide/GENOVA")`

```
Downloading GitHub repo robinweide/GENOVA@HEAD
Warning in system(full, intern = TRUE, ignore.stderr = quiet) :
  running command ''/usr/bin/git' ls-remote https://git.bioconductor.org/packages/rhdf5 RELEASE_3_20 2>/dev/null' had status 69
Error: Failed to install 'GENOVA' from GitHub:
  Command failed (69)
```
I also tried installing using devtools (`devtools::install_github("robinweide/GENOVA")`) as well as a local installation after downloading the repo (`devtools::install_local("path/to/GENOVA/GENOVA-master/")`) and get similar errors. I also managed to successfully install the rhdf5 package independently using BioCManager but this doesn't make a difference with installation of GENOVA. 

However, I can successfully install it without any issues in R 3.6.3 directly from github. Could you please clarify if the newer versions of R are not supported or is it something else? Please let me know if you need more information, thanks !

Cheers,
Jay

**Comment by teunbrand** [comment]
> Could you please clarify if the newer versions of R are not supported or is it something else

It should work on current R. I don't have any problems installing GENOVA locally on R 4.4.2 on Windows 11. From the error message, it appears the point of failure is a git operation. Are you able to install any other packages from GitHub?

**Comment by MuhundenJ** [comment]
Hi !

I can run `remotes::install_github("twitter/AnomalyDetection")` successfully

**Comment by MuhundenJ** [comment]
Hi !

Looks like the problem is that my RProject was on a separate network drive. I was able to install it successfully in a new local RProject. This is puzzling because the project location never interfered with install_github before. Equally puzzling is why it worked with R v3.6 but not others, despite the project directory being the same. Can't pinpoint the root cause but for now GENOVA appears to work. Thank you in any case !

Cheers,
Jay

**Comment by teunbrand** [comment]
Glad it worked out in the end!
