### ISSUE TITLE
RCP2 fails without chromsToUse

### ISSUE THREAD

**Issue by deWitLab** [robinweide/GENOVA#85]
I get the following error message when I do not use chromsToUse.

Error in `$<-.data.frame`(`*tmp*`, "color", value = "black") : 
  replacement has 1 row, data has 0

When I set chromsToUse the error message goes away.

**Comment by robinweide** [comment]
2d270e1f22088f8a125239eb4b724562174cb768 has brought a completely new version of RCP.
