### ISSUE TITLE
Cannot install package

### ISSUE THREAD

**Issue by cresswellkg** [robinweide/GENOVA#91]
I would like to use this package for analysis but can't seem to install it. I follow the vignette and run `devtools::install_github("robinweide/GENOVA", ref ="dev")`. This gives me the following errors:

1: In untar2(tarfile, files, list, exdir) :
  failed to copy ‘robinweide-GENOVA-5b82db0/vignettes/data//DATA/oidBackup/WAPL_Project/ChIP-seq/4aprilOp7AprilIGG/CTCF_WT/CTCF_WT_treat_pileup.bw’ to ‘robinweide-GENOVA-5b82db0/vignettes/data/CTCF_WT.bw’
2: In untar2(tarfile, files, list, exdir) :
  failed to copy ‘robinweide-GENOVA-5b82db0/vignettes/data//DATA/oidBackup/WAPL_Project/Hi-C/analysis/selected_regions/CTCF_WT_motifs.bed’ to ‘robinweide-GENOVA-5b82db0/vignettes/data/CTCF_WT_motifs.bed’
3: In untar2(tarfile, files, list, exdir) :
  failed to copy ‘robinweide-GENOVA-5b82db0/vignettes/data//DATA/oidBackup/Sanborn2015/GSE74072_Hap1_HiCCUPS_looplist.txt.gz’ to ‘robinweide-GENOVA-5b82db0/vignettes/data/GSE74072_Hap1_HiCCUPS_looplist.txt.gz’
4: In untar2(tarfile, files, list, exdir) :
  failed to copy ‘robinweide-GENOVA-5b82db0/vignettes/data//DATA/oidBackup/WAPL_Project/ChIP-seq/7april16/3892_5_Hap_H3K27ac_CGATGT_S89_L008_R1_001/MACS2_out/3892_5_Hap_H3K27ac_CGATGT_S89_L008_R1_001_peaks.narrowPeak’ to ‘robinweide-GENOVA-5b82db0/vignettes/data/H3K27ac_WT.narrowPeak’
5: In untar2(tarfile, files, list, exdir) :
  failed to copy ‘robinweide-GENOVA-5b82db0/vignettes/data//DATA/oidBackup/WAPL_Project/Hi-C/matrices/combined/SCC4KO/output/hic_results/matrix/SCC4KO/raw/10000/SCC4KO_10000_abs.bed’ to ‘robinweide-GENOVA-5b82db0/vignettes/data/SCC4_10kb_abs.bed’
6: In untar2(tarfile, files, list, exdir) :
  failed to copy ‘robinweide-GENOVA-5b82db0/vignettes/data//DATA/oidBackup/WAPL_Project/Hi-C/matrices/combined/SCC4KO/output/hic_results/matrix/SCC4KO/iced/10000/SCC4KO_10000_iced.matrix’ to ‘robinweide-GENOVA-5b82db0/vignettes/data/SCC4_10kb_iced.matrix’
7: In untar2(tarfile, files, list, exdir) :
  failed to copy ‘robinweide-GENOVA-5b82db0/vignettes/data//DATA/oidBackup/WAPL_Project/ChIP-seq/4aprilOp7AprilIGG/SMC1_WAPLKO/SMC1_WAPLKO_treat_pileup.bw’ to ‘robinweide-GENOVA-5b82db0/vignettes/data/SMC1_WAPL.bw’
8: In untar2(tarfile, files, list, exdir) :
  failed to copy ‘robinweide-GENOVA-5b82db0/vignettes/data//DATA/oidBackup/WAPL_Project/ChIP-seq/4aprilOp7AprilIGG/SMC1_WT/SMC1_WT_treat_pileup.bw’ to ‘robinweide-GENOVA-5b82db0/vignettes/data/SMC1_WT.bw’
9: In untar2(tarfile, files, list, exdir) :
  failed to copy ‘robinweide-GENOVA-5b82db0/vignettes/data//DATA/oidBackup/WAPL_Project/ChIP-seq/4aprilOp7AprilIGG/SMC1_WT/SMC1_WT_peaks.narrowPeak’ to ‘robinweide-GENOVA-5b82db0/vignettes/data/SMC1_WT_peaks.narrowPeak’
10: In untar2(tarfile, files, list, exdir) :
  failed to copy ‘robinweide-GENOVA-5b82db0/vignettes/data//DATA/oidBackup/WAPL_Project/Hi-C/matrices/combined/WaplKO/raw/1000000/WaplKO_combined_1000000_abs.bed’ to ‘robinweide-GENOVA-5b82db0/vignettes/data/WAPL_1000000_abs.bed’
11: In untar2(tarfile, files, list, exdir) :
  failed to copy ‘robinweide-GENOVA-5b82db0/vignettes/data//DATA/oidBackup/WAPL_Project/Hi-C/matrices/combined/WaplKO/iced/1000000/WaplKO_combined_1000000_iced.matrix’ to ‘robinweide-GENOVA-5b82db0/vignettes/data/WAPL_1000000_iced.matrix’
12: In untar2(tarfile, files, list, exdir) :
  failed to copy ‘robinweide-GENOVA-5b82db0/vignettes/data//DATA/oidBackup/WAPL_Project/Hi-C/matrices/combined/WaplKO/raw/10000/WaplKO_combined_10000_abs.bed’ to ‘robinweide-GENOVA-5b82db0/vignettes/data/WAPL_10000_abs.bed’
13: In untar2(tarfile, files, list, exdir) :
  failed to copy ‘robinweide-GENOVA-5b82db0/vignettes/data//DATA/oidBackup/WAPL_Project/Hi-C/matrices/combined/WaplKO/iced/10000/WaplKO_combined_10000_iced.matrix’ to ‘robinweide-GENOVA-5b82db0/vignettes/data/WAPL_10000_iced.matrix’
14: In untar2(tarfile, files, list, exdir) :
  failed to copy ‘robinweide-GENOVA-5b82db0/vignettes/data//DATA/oidBackup/WAPL_Project/Hi-C/matrices/combined/WaplKO/raw/40000/WaplKO_combined_40000_abs.bed’ to ‘robinweide-GENOVA-5b82db0/vignettes/data/WAPL_40000_abs.bed’
15: In untar2(tarfile, files, list, exdir) :
  failed to copy ‘robinweide-GENOVA-5b82db0/vignettes/data//DATA/oidBackup/WAPL_Project/Hi-C/matrices/combined/WaplKO/iced/40000/WaplKO_combined_40000_iced.matrix’ to ‘robinweide-GENOVA-5b82db0/vignettes/data/WAPL_40000_iced.matrix’
16: In untar2(tarfile, files, list, exdir) :
  failed to copy ‘robinweide-GENOVA-5b82db0/vignettes/data//DATA/oidBackup/WAPL_Project/Hi-C/matrices/combined/WT/combined/output/hic_results/matrix/WT/raw/1000000/WT_1000000_abs.bed’ to ‘robinweide-GENOVA-5b82db0/vignettes/data/WT_1000000_abs.bed’
17: In untar2(tarfile, files, list, exdir) :
  failed to copy ‘robinweide-GENOVA-5b82db0/vignettes/data//DATA/oidBackup/WAPL_Project/Hi-C/matrices/combined/WT/combined/output/hic_results/matrix/WT/iced/1000000/WT_1000000_iced.matrix’ to ‘robinweide-GENOVA-5b82db0/vignettes/data/WT_1000000_iced.matrix’
18: In untar2(tarfile, files, list, exdir) :
  failed to copy ‘robinweide-GENOVA-5b82db0/vignettes/data//DATA/oidBackup/WAPL_Project/Hi-C/matrices/combined/WT/combined/output/hic_results/matrix/WT/raw/10000/WT_10000_abs.bed’ to ‘robinweide-GENOVA-5b82db0/vignettes/data/WT_10000_abs.bed’
19: In untar2(tarfile, files, list, exdir) :
  failed to copy ‘robinweide-GENOVA-5b82db0/vignettes/data//DATA/oidBackup/WAPL_Project/Hi-C/matrices/combined/WT/combined/output/hic_results/matrix/WT/iced/10000/WT_10000_iced.matrix’ to ‘robinweide-GENOVA-5b82db0/vignettes/data/WT_10000_iced.matrix’
20: In untar2(tarfile, files, list, exdir) :
  failed to copy ‘robinweide-GENOVA-5b82db0/vignettes/data//DATA/oidBackup/WAPL_Project/Hi-C/analysis/extendedLoops/WT_3Mb_extended_loops.bed’ to ‘robinweide-GENOVA-5b82db0/vignettes/data/WT_3Mb_extended_loops.bed’
21: In untar2(tarfile, files, list, exdir) :
  failed to copy ‘robinweide-GENOVA-5b82db0/vignettes/data//DATA/oidBackup/WAPL_Project/Hi-C/matrices/combined/WT/combined/output/hic_results/matrix/WT/raw/40000/WT_40000_abs.bed’ to ‘robinweide-GENOVA-5b82db0/vignettes/data/WT_40000_abs.bed’
22: In untar2(tarfile, files, list, exdir) :
  failed to copy ‘robinweide-GENOVA-5b82db0/vignettes/data//DATA/oidBackup/WAPL_Project/Hi-C/matrices/combined/WT/combined/output/hic_results/matrix/WT/iced/40000/WT_40000_iced.matrix’ to ‘robinweide-GENOVA-5b82db0/vignettes/data/WT_40000_iced.matrix’
23: In untar2(tarfile, files, list, exdir) :
  failed to copy ‘robinweide-GENOVA-5b82db0/vignettes/data//DATA/oidBackup/WAPL_Project/Hi-C/analysis/HICCUPS/WT_rep123.hiccups.bedpe_5k10k25k_merged.bedpe’ to ‘robinweide-GENOVA-5b82db0/vignettes/data/WT_HICCUPS.bedpe’
24: In untar2(tarfile, files, list, exdir) :
  failed to copy ‘robinweide-GENOVA-5b82db0/vignettes/data//DATA/oidBackup/WAPL_Project/Hi-C/analysis/HiCseg/WT.bed’ to ‘robinweide-GENOVA-5b82db0/vignettes/data/WT_hicseg_TADs.bed’
25: In untar2(tarfile, files, list, exdir) :
  failed to copy ‘robinweide-GENOVA-5b82db0/vignettes/data//DATA/references/human/hg19/cytobandAcen.bed’ to ‘robinweide-GENOVA-5b82db0/vignettes/data/hg19_cytobandAcen.bed’
26: In untar2(tarfile, files, list, exdir) :
  failed to copy ‘robinweide-GENOVA-5b82db0/vignettes/data//DATA/projects/Wapl/superEnhancerWT/Hap1/superEnhancers.txt’ to ‘robinweide-GENOVA-5b82db0/vignettes/data/homerSuperEnhancers.txt’
27: In file(name, "wb") :
  cannot open file 'robinweide-GENOVA-5b82db0/vignettes/data/nintchdbpict000277131838.jpg?w=811': Invalid argument

**Comment by robinweide** [comment]
Hi Kellen,

I just tried `devtools::install_github("robinweide/GENOVA", ref ="dev")` on a local laptop and it installs fine. 

It seems that you are trying to build the vignette too. Could you try to run `devtools::install_github("robinweide/GENOVA", quick = TRUE)` and see if that works?

Cheers,
Robin

**Comment by cresswellkg** [comment]
Robin,

I tried to run it with `devtools::install_github("robinweide/GENOVA", quick = TRUE)` and it still returns the same errors. I've also tried it with the `build_vignette=FALSE`. I'm running it on a Windows machine, could this be the issue?

Thanks,
Kellen

**Comment by robinweide** [comment]
It could very well be, as it seems to install fine on Linux/OSX. 

Maybe it cannot handle the symlinks. I made a new branch without them: could you please install with
 `devtools::install_github("robinweide/GENOVA", quick = TRUE, ref = "noSymlinks")`

**Comment by cresswellkg** [comment]
I now get this error:

cannot open file 'robinweide-GENOVA-481aa26/vignettes/data/nintchdbpict000277131838.jpg?w=811': Invalid argument

**Comment by robinweide** [comment]
Yes, I missed that line in your error-log. I fixed that too now. Please try `devtools::install_github("robinweide/GENOVA", quick = TRUE, ref = "noSymlinks")` again.

**Comment by cresswellkg** [comment]
It works now.

Thanks so much!

**Comment by robinweide** [comment]
Awesome!

Happy to help. Please tell me when other questions/suggestions pop up.
