### ISSUE TITLE
Outlier-correction for negative numbers (i.e. Z-score)

### ISSUE THREAD

**Issue by robinweide** [robinweide/GENOVA#93]
In ATA, APA and PE-SCAn, a user could decide to use an expObject with Z-score normalised data. The outlier-corrections only filter out values _larger_ that 99.5% of the data.

**Comment by teunbrand** [comment]
This is now possible for PESCAn and APA by providing the `outlier_filter` argument.

**Comment by teunbrand** [comment]
I think this now exists for the relevant functions.
